# Machine Learning Models

In [3]:
%%time

%pip install xgboost

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import gc
import re
import random
from IPython.display import display, HTML
import openpyxl
from sklearn.metrics import (r2_score,mean_absolute_error,mean_squared_error,mean_tweedie_deviance)
from sklearn.model_selection import ParameterGrid, ParameterSampler
from functools import partial

# Pandas DataFrames and Series
pd.set_option("display.float_format",lambda x: f"{x:,.5f}")

# NumPy arrays
np.set_printoptions(suppress=True,precision=6)

# Matplotlib axes
plt.rcParams["axes.formatter.useoffset"] = False
plt.rcParams["axes.formatter.limits"] = (-10, 10)

df = pd.read_csv("crypto_master_dataset_imputed.csv")
list(df.columns)

CPU times: total: 52.2 s
Wall time: 54.5 s

['coin',
 'timestamp',
 'open',
 'high',
 'low',
 'close',
 'ohlcv_volume',
 'momentum_5m',
 'momentum_15m',
 'realized_vol_5m',
 'realized_vol_15m',
 'best_bid',
 'best_ask',
 'spread',
 'spread_pct',
 'bid_depth_top5',
 'ask_depth_top5',
 'bid_depth_top10',
 'ask_depth_top10',
 'order_book_imbalance_top5',
 'order_book_imbalance_top10',
 'open_interest',
 'funding_rate',
 'cumulative_funding',
 'long_account',
 'short_account',
 'long_short_ratio',
 'long_short_skew',
 'liquidation_volume',
 'liquidation_acceleration_5m',
 'liquidation_acceleration_15m',
 'whale_tx_count_100k',
 'whale_tx_count_1m',
 'active_addresses_24h',
 'transaction_volume',
 'social_volume',
 'social_dominance',
 'sentiment_polarity',
 'abnormal_attention',
 'liq_vol_zscore',
 'liq_vol_bucket',
 'liq_vol_flag',
 'long_short_new_observation',
 'oi_momentum_5m',
 'oi_momentum_15m',
 'oi_pct_change_5m',
 'oi_pct_change_15m',
 'oi_zscore_15m',
 'oi_zscore_1h',
 'oi_zscore_3h',
 'price_segment_id',
 'volatility_acceleration',
 'volatility_ratio',
 'oi_acceleration',
 'spread_volatility_ratio',
 'oi_volatility_interaction',
 'total_depth_top5',
 'total_depth_top10']

In [4]:
%%time


# ============================================================
# 1. Configuration
# ============================================================

SEED = 42

random.seed(SEED)
np.random.seed(SEED)

HORIZON = 12
SEQUENCE_LENGTH = 60

TRAIN_FRACTION = 0.70
VALIDATION_FRACTION = 0.15

TABULAR_LAGS = [12,48]
TARGET_COL = "target_cumulative_liq_volume_next_12row"

model_df = df.copy()

EXCLUDE_COIN = False # Only mark as true when excluding coin during ablation study script!
    
# ============================================================
# 2. Clean and sort
# ============================================================

model_df["timestamp"] = pd.to_datetime(model_df["timestamp"],utc=True,errors="coerce")
model_df["liquidation_volume"] = pd.to_numeric(model_df["liquidation_volume"],errors="coerce")

model_df = (model_df.dropna(subset=["coin","timestamp","price_segment_id","liquidation_volume"])
            .sort_values(["coin","timestamp","price_segment_id"]).reset_index(drop=True))

# ============================================================
# 3. Add time features
# ============================================================

model_df["hour"] = model_df["timestamp"].dt.hour
model_df["minute"] = model_df["timestamp"].dt.minute
model_df["day_of_week"] = model_df["timestamp"].dt.dayofweek

model_df["hour_sin"] = np.sin(2 * np.pi * model_df["hour"] / 24)
model_df["hour_cos"] = np.cos(2 * np.pi * model_df["hour"] / 24)
model_df["minute_sin"] = np.sin(2 * np.pi * model_df["minute"] / 60)
model_df["minute_cos"] = np.cos(2 * np.pi * model_df["minute"] / 60)
model_df["day_sin"] = np.sin(2 * np.pi * model_df["day_of_week"] / 7)
model_df["day_cos"] = np.cos(2 * np.pi * model_df["day_of_week"] / 7)

# ============================================================
# 4. Create the cumulative future target
# ============================================================

# liquidation volume is calculated as the sum from T+1 to T+12 steps
def future_rolling_sum(series, horizon):
    return (series.shift(-1).iloc[::-1].rolling(window=horizon,min_periods=horizon).sum().iloc[::-1])

segment_keys = ["coin","price_segment_id"]

# Grouping by "price segment" prevents the target crossing periods where price data was missing
model_df[TARGET_COL] = (model_df.groupby(["coin","price_segment_id"],sort=False,observed=True)["liquidation_volume"]
                        .transform(lambda series: future_rolling_sum(series,HORIZON)))

# Any rows without a complete future 12-row window are removed
model_df = (model_df.dropna(subset=[TARGET_COL]).reset_index(drop=True))

# here is another check to ensure the target variable is never negative
model_df[TARGET_COL] = (model_df[TARGET_COL].clip(lower=0).astype("float32"))

# ============================================================
# 5. Create naive previous-12-row persistence baseline
# ============================================================

NAIVE_BASELINE_COL = "naive_previous_12row_liq_sum"
# for a given row t, this is taking the sum from t-11 to t
model_df[NAIVE_BASELINE_COL] = (model_df.groupby(segment_keys,sort=False,observed=True)["liquidation_volume"]
                                .transform(lambda series: (series.rolling(window=HORIZON,min_periods=HORIZON).sum())).astype("float32"))

# ============================================================
# 6. Define feature groups
# ============================================================

FEATURE_GROUPS = {
    
    "price_volume": [
        "ohlcv_volume",
        "momentum_5m",
        "momentum_15m",
        "realized_vol_5m",
        "realized_vol_15m",
        "volatility_acceleration",
        "volatility_ratio"
    ],

    "order_book": [
        "spread_pct",
        "total_depth_top5",
        "total_depth_top10",
        "order_book_imbalance_top5",
        "order_book_imbalance_top10",
        "spread_volatility_ratio"
    ],

    "open_interest": [
        "open_interest",
        "oi_momentum_5m",
        "oi_momentum_15m",
        "oi_pct_change_5m",
        "oi_pct_change_15m",
        "oi_zscore_15m",
        "oi_zscore_1h",
        "oi_zscore_3h",
        "oi_acceleration",
        "oi_volatility_interaction"
    ],

    "funding_positioning": [
        "funding_rate",
        "long_short_ratio",
        "long_short_skew"
    ],

    "onchain_activity": [
        "whale_tx_count_100k",
        "whale_tx_count_1m",
        "active_addresses_24h",
        "transaction_volume"
    ],

    "social": [
        "social_volume",
        "social_dominance",
        "sentiment_polarity",
        "abnormal_attention"
    ],

    "time": [
        "hour_sin",
        "hour_cos",
        "minute_sin",
        "minute_cos",
        "day_sin",
        "day_cos"
    ]
}

# ============================================================
# 7. Identify available modelling features
# ============================================================

# Coin identity is handled separately through dummy encoding later.
available_feature_groups = {}
for group_name, group_columns in FEATURE_GROUPS.items():
    available_columns = [column for column in group_columns if column in model_df.columns]
    available_feature_groups[group_name] = (available_columns)


# Flatten all available non-coin feature groups into one list.
# These are the numeric predictors used by both the LSTM and the tabular models.
base_feature_cols = list(dict.fromkeys(column for group_columns in available_feature_groups.values() for column in group_columns))

# ============================================================
# 8. Define variables receiving explicit tabular lags
# ============================================================

preferred_lag_sources = [
    "ohlcv_volume",
    "momentum_5m",
    "momentum_15m",
    "realized_vol_5m",
    "realized_vol_15m",
    "spread_pct",
    "total_depth_top5",
    "total_depth_top10",
    "order_book_imbalance_top5",
    "order_book_imbalance_top10",
    "open_interest",
    "oi_momentum_5m",
    "oi_momentum_15m",
    "oi_pct_change_5m",
    "oi_pct_change_15m",
    "oi_zscore_15m",
    "oi_zscore_1h",
    "oi_zscore_3h",
    "social_volume",
    "social_dominance",
    "sentiment_polarity",
    "abnormal_attention",
    "volatility_acceleration",
    "volatility_ratio",
    "spread_volatility_ratio",
    "oi_acceleration",
    "oi_volatility_interaction"
]

tabular_lag_source_cols = [column for column in preferred_lag_sources if column in model_df.columns]

# ============================================================
# 9. Create lags within coin and price segments
# ============================================================

segment_group = model_df.groupby(segment_keys,sort=False,observed=True)

lag_frames = []
for lag in TABULAR_LAGS:

    lag_frame = (segment_group[tabular_lag_source_cols].shift(lag))

    lag_frame.columns = [f"{column}_lag{lag}"for column in tabular_lag_source_cols]

    lag_frames.append(lag_frame.astype("float32"))

generated_lag_cols = [column for lag_frame in lag_frames for column in lag_frame.columns]

model_df = pd.concat([model_df, *lag_frames],axis=1,copy=False)

del segment_group
del lag_frames
del lag_frame
gc.collect()

# ============================================================
# 10. Add segment-position metadata
# ============================================================

# this is used later as we need enough seequence lengths for lags and LSTM inputs
model_df["segment_position"] = (model_df.groupby(segment_keys,sort=False,observed=True).cumcount().astype("int32"))

# ============================================================
# 11. Split data into train/validation/test
# ============================================================

# -1 represents all rows which will be removed, as their next 12 rows would fall into the next batch of data, therefore resulting in leakage
#  0 = training data
#  1 = validation data
#  2 = test data

model_df["split_id"] = np.int8(-1)

for coin, coin_df in model_df.groupby("coin",sort=False,observed=True):
    
    coin_indices = coin_df.index.to_numpy(dtype=np.int64)
    number_of_rows = len(coin_indices)

    train_end = int(number_of_rows * TRAIN_FRACTION)
    train_stop = max(0,train_end - HORIZON)

    validation_end = int(number_of_rows*(TRAIN_FRACTION+VALIDATION_FRACTION))
    validation_stop = max(train_end,validation_end - HORIZON)

    model_df.loc[coin_indices[:train_stop],"split_id"] = 0
    model_df.loc[coin_indices[train_end:validation_stop],"split_id"] = 1
    model_df.loc[coin_indices[validation_end:],"split_id"] = 2

# ============================================================
# 12. Define identical non-overlapping prediction endpoints
# ============================================================

# A tabular endpoint needs enough history for the longest lag.
# An LSTM endpoint needs SEQUENCE_LENGTH consecutive historical rows.
minimum_history = max(SEQUENCE_LENGTH - 1,max(TABULAR_LAGS))

valid_endpoint = (
    (model_df["segment_position"] >= minimum_history) & # checks it has sufficient length
    (model_df["segment_position"].mod(HORIZON).eq(0))   # prevents the overlap by spacing out by horizon
)

train_idx = model_df.index[(model_df["split_id"] == 0) & valid_endpoint].to_numpy(dtype=np.int64) 
val_idx = model_df.index[(model_df["split_id"] == 1) & valid_endpoint].to_numpy(dtype=np.int64)
test_idx = model_df.index[(model_df["split_id"] == 2) & valid_endpoint].to_numpy(dtype=np.int64)

print("Training:", f"{len(train_idx):,}")
print("Validation:", f"{len(val_idx):,}")
print("Test:", f"{len(test_idx):,}")

# ============================================================
# 13. Fit feature preprocessing using training data only
# ============================================================

# Use the full pre-validation training period to estimate medians, means and standard deviations.
preprocessing_train_idx = model_df.index[model_df["split_id"] == 0].to_numpy(dtype=np.int64)

def fit_feature_statistics(data,columns,fit_indices,):
    retained_columns = []
    statistics = {}

    for column in columns:

        training_values = pd.to_numeric(data.loc[fit_indices,column],errors="coerce").replace([np.inf, -np.inf],np.nan)

        unique_count = (training_values.nunique(dropna=True))

        if unique_count <= 1:
            continue

        median = float(training_values.median())

        filled_values = (training_values.fillna(median))

        mean = float(filled_values.mean())

        standard_deviation = float(filled_values.std(ddof=0))

        if (not np.isfinite(standard_deviation)or standard_deviation == 0):
            continue

        retained_columns.append(column)

        statistics[column] = {"median": median, "mean": mean,"standard_deviation":standard_deviation}

    return retained_columns, statistics

# Base features are used by the LSTM sequence
sequence_numeric_cols, sequence_feature_statistics = (fit_feature_statistics(data=model_df,columns=base_feature_cols,fit_indices=preprocessing_train_idx,))

# Tabular models use base features plus explicit lags
retained_lag_cols, lag_feature_statistics = (fit_feature_statistics(data=model_df,columns=generated_lag_cols,fit_indices=preprocessing_train_idx,))

tabular_numeric_cols = (sequence_numeric_cols + retained_lag_cols)

tabular_feature_statistics = {**sequence_feature_statistics,**lag_feature_statistics}

print("\nSequence numeric predictors:",len(sequence_numeric_cols))

print("Tabular numeric predictors:",len(tabular_numeric_cols))

# ============================================================
# 14. Create common coin dummy variables
# ============================================================

coin_categories = sorted(model_df.loc[preprocessing_train_idx,"coin"].astype(str).unique())

# if we exclude the coin from model features, then we dont create encoded features for them
coin_dummy_categories = ([] if EXCLUDE_COIN else coin_categories[1:])

coin_dummy_names = [f"coin_{category}"for category in coin_dummy_categories]

# Register the encoded coin columns as their own feature group
available_feature_groups["coin"] = (coin_dummy_names.copy())

# ============================================================
# 15. Standardised matrix builder
# ============================================================

def build_standardised_matrix(data,indices,numeric_columns,feature_statistics,dummy_categories):
    
    number_of_rows = len(indices)

    number_of_columns = (len(numeric_columns) + len(dummy_categories))

    X = np.empty((number_of_rows,number_of_columns),dtype=np.float32)

    # Numeric features
    for column_number, column in enumerate(numeric_columns):
        
        values = pd.to_numeric(data.loc[indices,column],errors="coerce").to_numpy(dtype=np.float32,copy=True)

        statistics = (feature_statistics[column])

        invalid_mask = ~np.isfinite(values) # checks if the value is a finite number

        values[invalid_mask] = (statistics["median"]) # if value is not a finite number, then we use the median for imputation
        values = (values - statistics["mean"]) / statistics["standard_deviation"] # calculate z-scores and overwrites median with this
        values = np.clip(values,-10,10) # exclude extreme z-score values
        X[:, column_number] = values # assign values back into dataset

    # Add the coin dummy variables
    selected_coins = (data.loc[indices,"coin"].astype(str).to_numpy())
    for dummy_number, category in enumerate(dummy_categories):
        X[:,len(numeric_columns) + dummy_number] = (selected_coins == category).astype("float32")
        
    return X

sequence_feature_names = (sequence_numeric_cols + coin_dummy_names)

tabular_feature_names = (tabular_numeric_cols + coin_dummy_names)


# ============================================================
# 16. Build common tabular matrices
# ============================================================

X_train_tabular = build_standardised_matrix(
    data=model_df,
    indices=train_idx,
    numeric_columns=tabular_numeric_cols,
    feature_statistics=tabular_feature_statistics,
    dummy_categories=coin_dummy_categories
)

X_val_tabular = build_standardised_matrix(
    data=model_df,
    indices=val_idx,
    numeric_columns=tabular_numeric_cols,
    feature_statistics=tabular_feature_statistics,
    dummy_categories=coin_dummy_categories
)

X_test_tabular = build_standardised_matrix(
    data=model_df,
    indices=test_idx,
    numeric_columns=tabular_numeric_cols,
    feature_statistics=tabular_feature_statistics,
    dummy_categories=coin_dummy_categories
)


# ============================================================
# 17. Build common sequence feature matrix
# ============================================================

all_row_indices = np.arange(
    len(model_df),
    dtype=np.int64
)

X_sequence_all = build_standardised_matrix(
    data=model_df,
    indices=all_row_indices,
    numeric_columns=sequence_numeric_cols,
    feature_statistics=sequence_feature_statistics,
    dummy_categories=coin_dummy_categories
)


# ============================================================
# 18. Create common target arrays
# ============================================================

y_all = model_df[TARGET_COL].to_numpy(dtype=np.float32)

y_train = y_all[train_idx]
y_val = y_all[val_idx]
y_test = y_all[test_idx]

# ============================================================
# 19. Create naive baseline prediction arrays
# ============================================================

naive_predictions_all = (model_df[NAIVE_BASELINE_COL].to_numpy(dtype=np.float32))
naive_train_pred = naive_predictions_all[train_idx]
naive_val_pred = naive_predictions_all[val_idx]
naive_test_pred = naive_predictions_all[test_idx]

# ============================================================
# 20. Final leakage checks
# ============================================================

all_predictor_names = list(dict.fromkeys(sequence_feature_names + tabular_feature_names))

print("\nTarget diagnostics")
print("Training mean:", y_train.mean())
print("Validation mean:", y_val.mean())
print("Test mean:", y_test.mean())
print("Training median:", np.median(y_train))

Training: 208,143
Validation: 44,604
Test: 44,614

Sequence numeric predictors: 40
Tabular numeric predictors: 92

Target diagnostics
Training mean: 37483.086
Validation mean: 25954.371
Test mean: 48937.984
Training median: 103.82607
CPU times: total: 1min 26s
Wall time: 1min 30s

In [5]:
list(model_df.columns)

['coin',
 'timestamp',
 'open',
 'high',
 'low',
 'close',
 'ohlcv_volume',
 'momentum_5m',
 'momentum_15m',
 'realized_vol_5m',
 'realized_vol_15m',
 'best_bid',
 'best_ask',
 'spread',
 'spread_pct',
 'bid_depth_top5',
 'ask_depth_top5',
 'bid_depth_top10',
 'ask_depth_top10',
 'order_book_imbalance_top5',
 'order_book_imbalance_top10',
 'open_interest',
 'funding_rate',
 'cumulative_funding',
 'long_account',
 'short_account',
 'long_short_ratio',
 'long_short_skew',
 'liquidation_volume',
 'liquidation_acceleration_5m',
 'liquidation_acceleration_15m',
 'whale_tx_count_100k',
 'whale_tx_count_1m',
 'active_addresses_24h',
 'transaction_volume',
 'social_volume',
 'social_dominance',
 'sentiment_polarity',
 'abnormal_attention',
 'liq_vol_zscore',
 'liq_vol_bucket',
 'liq_vol_flag',
 'long_short_new_observation',
 'oi_momentum_5m',
 'oi_momentum_15m',
 'oi_pct_change_5m',
 'oi_pct_change_15m',
 'oi_zscore_15m',
 'oi_zscore_1h',
 'oi_zscore_3h',
 'price_segment_id',
 'volatility_acceleration',
 'volatility_ratio',
 'oi_acceleration',
 'spread_volatility_ratio',
 'oi_volatility_interaction',
 'total_depth_top5',
 'total_depth_top10',
 'hour',
 'minute',
 'day_of_week',
 'hour_sin',
 'hour_cos',
 'minute_sin',
 'minute_cos',
 'day_sin',
 'day_cos',
 'target_cumulative_liq_volume_next_12row',
 'naive_previous_12row_liq_sum',
 'ohlcv_volume_lag12',
 'momentum_5m_lag12',
 'momentum_15m_lag12',
 'realized_vol_5m_lag12',
 'realized_vol_15m_lag12',
 'spread_pct_lag12',
 'total_depth_top5_lag12',
 'total_depth_top10_lag12',
 'order_book_imbalance_top5_lag12',
 'order_book_imbalance_top10_lag12',
 'oi_momentum_5m_lag12',
 'oi_momentum_15m_lag12',
 'oi_pct_change_5m_lag12',
 'oi_pct_change_15m_lag12',
 'oi_zscore_15m_lag12',
 'oi_zscore_1h_lag12',
 'oi_zscore_3h_lag12',
 'social_volume_lag12',
 'social_dominance_lag12',
 'sentiment_polarity_lag12',
 'abnormal_attention_lag12',
 'volatility_acceleration_lag12',
 'volatility_ratio_lag12',
 'spread_volatility_ratio_lag12',
 'oi_acceleration_lag12',
 'oi_volatility_interaction_lag12',
 'ohlcv_volume_lag48',
 'momentum_5m_lag48',
 'momentum_15m_lag48',
 'realized_vol_5m_lag48',
 'realized_vol_15m_lag48',
 'spread_pct_lag48',
 'total_depth_top5_lag48',
 'total_depth_top10_lag48',
 'order_book_imbalance_top5_lag48',
 'order_book_imbalance_top10_lag48',
 'oi_momentum_5m_lag48',
 'oi_momentum_15m_lag48',
 'oi_pct_change_5m_lag48',
 'oi_pct_change_15m_lag48',
 'oi_zscore_15m_lag48',
 'oi_zscore_1h_lag48',
 'oi_zscore_3h_lag48',
 'social_volume_lag48',
 'social_dominance_lag48',
 'sentiment_polarity_lag48',
 'abnormal_attention_lag48',
 'volatility_acceleration_lag48',
 'volatility_ratio_lag48',
 'spread_volatility_ratio_lag48',
 'oi_acceleration_lag48',
 'oi_volatility_interaction_lag48',
 'segment_position',
 'split_id']

### Model 1: XG Boost

In [4]:
%%time

from xgboost import (XGBClassifier,XGBRegressor)

# ============================================================
# 1. Configuration
# ============================================================

XGB_TUNING_TRIALS = 30
XGB_MAX_ESTIMATORS = 2000
XGB_EARLY_STOPPING_ROUNDS = 50

# ============================================================
# 2. Define hurdle targets
# ============================================================

xgb_y_train_positive = (y_train > 0).astype("int8")
xgb_y_val_positive = (y_val > 0).astype("int8")
xgb_positive_train_mask = (y_train > 0)
xgb_positive_val_mask = (y_val > 0)

xgb_negative_count = (xgb_y_train_positive == 0).sum()
xgb_positive_count = (xgb_y_train_positive == 1).sum()
xgb_imbalance_ratio = (xgb_negative_count/ xgb_positive_count)
print("Training positive rate:",xgb_y_train_positive.mean())
print("Validation positive rate:",xgb_y_val_positive.mean())

# ============================================================
# 3. Define hyperparameter grid
# ============================================================

xgb_joint_param_space = {
    "learning_rate": [0.01,0.03,0.05,0.10],
    "max_depth": [3,4,6,8],
    "min_child_weight": [5,10,20,50,100],
    "subsample": [0.60,0.80,1.00],
    "colsample_bytree": [0.60,0.80,1.00],
    "gamma": [0.0,0.1,0.5,1.0],
    "reg_alpha": [0.0,0.01,0.10,1.0],
    "reg_lambda": [0.5,1.0,2.0,5.0,10.0],
    "scale_pos_weight": [1.0,np.sqrt(xgb_imbalance_ratio),xgb_imbalance_ratio / 2,xgb_imbalance_ratio], # Classifier-specific parameter
    "tweedie_variance_power": [1.1,1.3,1.5,1.7,1.9] # Regressor-specific parameter
}

xgb_parameter_trials = list(ParameterSampler(xgb_joint_param_space,n_iter=XGB_TUNING_TRIALS,random_state=SEED))

print("Number of tuning trials:",len(xgb_parameter_trials))

# ============================================================
# 4. tuning results storage objects
# ============================================================

xgb_tuning_results = []

# Selectin is based on best RMSE
xgb_best_val_rmse = np.inf

xgb_best_event_model = None
xgb_best_size_model = None
xgb_best_params = None
xgb_best_val_pred = None

# ============================================================
# 5. Joint random search
# ============================================================

for trial_number, params in enumerate(xgb_parameter_trials,start=1):

    print(f"\nTrial {trial_number} "f"of {XGB_TUNING_TRIALS}")
    print(params)

    # ============================================================
    # A. Train event occurrence classifier
    # ============================================================

    candidate_event_model = XGBClassifier(objective="binary:logistic",
                                          n_estimators=XGB_MAX_ESTIMATORS,learning_rate=params["learning_rate"],
                                          max_depth=params["max_depth"],
                                          min_child_weight=params["min_child_weight"],
                                          subsample=params["subsample"],
                                          colsample_bytree=params["colsample_bytree"],
                                          gamma=params["gamma"],
                                          reg_alpha=params["reg_alpha"],
                                          reg_lambda=params["reg_lambda"],
                                          scale_pos_weight=params["scale_pos_weight"],
                                          tree_method="hist",
                                          eval_metric="aucpr",
                                          early_stopping_rounds=(XGB_EARLY_STOPPING_ROUNDS),
                                          random_state=SEED,
                                          n_jobs=-1)

    candidate_event_model.fit(X_train_tabular,
                              xgb_y_train_positive,
                              eval_set=[(X_val_tabular,xgb_y_val_positive)],
                              verbose=False)

    # ============================================================
    # B. Train positive volume regressor
    # ============================================================

    tweedie_power = params["tweedie_variance_power"]

    candidate_size_model = XGBRegressor(objective="reg:tweedie",
                                        tweedie_variance_power=(tweedie_power),
                                        n_estimators=XGB_MAX_ESTIMATORS,
                                        learning_rate=params["learning_rate"],
                                        max_depth=params["max_depth"],
                                        min_child_weight=params["min_child_weight"],
                                        subsample=params["subsample"],
                                        colsample_bytree=params["colsample_bytree"],
                                        gamma=params["gamma"],
                                        reg_alpha=params["reg_alpha"],
                                        reg_lambda=params["reg_lambda"],
                                        tree_method="hist",
                                        eval_metric=(f"tweedie-nloglik@"f"{tweedie_power}"),
                                        early_stopping_rounds=(XGB_EARLY_STOPPING_ROUNDS),
                                        random_state=SEED,
                                        n_jobs=-1)


    candidate_size_model.fit(X_train_tabular[xgb_positive_train_mask],
                            y_train[xgb_positive_train_mask],
                            eval_set=[(X_val_tabular[xgb_positive_val_mask],y_val[xgb_positive_val_mask])],
                            verbose=False)

    # ============================================================
    # C. Validation prediction
    # ============================================================

    candidate_val_event_probability = (candidate_event_model.predict_proba(X_val_tabular)[:, 1])
    candidate_val_conditional_amount = np.clip(candidate_size_model.predict(X_val_tabular ),0,None )
    candidate_val_pred = (candidate_val_event_probability * candidate_val_conditional_amount)
    candidate_val_pred = np.asarray(candidate_val_pred,dtype=np.float64).reshape(-1)

    # ============================================================
    # D. Calculate evaluation metrics
    # ============================================================

    candidate_val_r2 = r2_score(y_val,candidate_val_pred)
    candidate_val_mae = mean_absolute_error(y_val,candidate_val_pred)
    candidate_val_rmse = np.sqrt(mean_squared_error(y_val,candidate_val_pred))

    trial_result = {"trial": trial_number,
                    "validation_rmse": candidate_val_rmse,
                    "validation_mae": candidate_val_mae,
                    "validation_r2": candidate_val_r2,
                    "event_best_iteration": (candidate_event_model.best_iteration),
                    "size_best_iteration": (candidate_size_model.best_iteration),
                    **params}
            
    xgb_tuning_results.append(trial_result)

    print(f"Validation RMSE: "f"{candidate_val_rmse:.6f}")
    print(f"Validation MAE: "f"{candidate_val_mae:.6f}")
    print(f"Validation R²: "f"{candidate_val_r2:.6f}")

    # ============================================================
    # E. Keep track of best model based on RMSE
    # ============================================================

    if candidate_val_rmse < xgb_best_val_rmse:

        if xgb_best_event_model is not None: del xgb_best_event_model
        if xgb_best_size_model is not None: del xgb_best_size_model

        xgb_best_val_rmse = candidate_val_rmse
        xgb_best_event_model = (candidate_event_model)
        xgb_best_size_model = (candidate_size_model)
        xgb_best_params = params.copy()
        xgb_best_val_pred = (candidate_val_pred.copy())

        print("New best model found.")

    else:

        del candidate_event_model
        del candidate_size_model

    gc.collect()

# ============================================================
# 6. Create tuning results table
# ============================================================

xgb_tuning_results_df = pd.DataFrame(xgb_tuning_results).sort_values("validation_rmse",ascending=True).reset_index(drop=True)

print("\nTop tuning results:")

display(xgb_tuning_results_df.head(10))

print("\nBest validation RMSE:",xgb_best_val_rmse)
print("\nBest parameters:")
print(xgb_best_params)


# ============================================================
# 7. Name final selected models
# ============================================================

xgb_event_model = (xgb_best_event_model)
xgb_size_model = (xgb_best_size_model)
xgb_val_pred = (xgb_best_val_pred)

# ============================================================
# 8. Generate untouched test predictions
# ============================================================

xgb_test_event_probability = (xgb_event_model.predict_proba(X_test_tabular)[:, 1])
xgb_test_conditional_amount = np.clip(xgb_size_model.predict(X_test_tabular),0,None)
xgb_test_pred = (xgb_test_event_probability * xgb_test_conditional_amount)
xgb_test_pred = np.asarray(xgb_test_pred,dtype=np.float64).reshape(-1)

# ============================================================
# 9. Final validation and test results
# ============================================================

xgb_final_val_rmse = np.sqrt(mean_squared_error(y_val,xgb_val_pred))
xgb_final_val_mae = mean_absolute_error(y_val,xgb_val_pred)
xgb_final_val_r2 = r2_score(y_val,xgb_val_pred)
xgb_final_test_rmse = np.sqrt(mean_squared_error(y_test,xgb_test_pred))
xgb_final_test_mae = mean_absolute_error(y_test,xgb_test_pred)
xgb_final_test_r2 = r2_score(y_test,xgb_test_pred)

print("\nFinal selected XGBoost model")
print(f"Validation RMSE: "f"{xgb_final_val_rmse:.6f}")
print(f"Validation MAE: "f"{xgb_final_val_mae:.6f}")
print(f"Validation R²: "f"{xgb_final_val_r2:.6f}")
print(f"\nTest RMSE: "f"{xgb_final_test_rmse:.6f}")
print(f"Test MAE: "f"{xgb_final_test_mae:.6f}")
print(f"Test R²: "f"{xgb_final_test_r2:.6f}")

Training positive rate: 0.5571650259677241
Validation positive rate: 0.4828042328042328
Class imbalance ratio: 0.7948003794084677
Number of tuning trials: 30

Trial 1 of 30
{'tweedie_variance_power': 1.7, 'subsample': 0.8, 'scale_pos_weight': np.float64(0.39740018970423385), 'reg_lambda': 2.0, 'reg_alpha': 0.1, 'min_child_weight': 10, 'max_depth': 3, 'learning_rate': 0.03, 'gamma': 0.1, 'colsample_bytree': 0.6}
Validation RMSE: 166007.097654
Validation MAE: 28078.067354
Validation R²: 0.092953
New best model found.

Trial 2 of 30
{'tweedie_variance_power': 1.1, 'subsample': 1.0, 'scale_pos_weight': np.float64(0.7948003794084677), 'reg_lambda': 0.5, 'reg_alpha': 0.01, 'min_child_weight': 100, 'max_depth': 8, 'learning_rate': 0.1, 'gamma': 0.5, 'colsample_bytree': 0.8}
Validation RMSE: 167053.396129
Validation MAE: 29716.380979
Validation R²: 0.081483

Trial 3 of 30
{'tweedie_variance_power': 1.5, 'subsample': 0.8, 'scale_pos_weight': np.float64(0.7948003794084677), 'reg_lambda': 5.0, 'reg_alpha': 1.0, 'min_child_weight': 100, 'max_depth': 4, 'learning_rate': 0.03, 'gamma': 0.1, 'colsample_bytree': 0.6}
Validation RMSE: 165845.509183
Validation MAE: 29364.686628
Validation R²: 0.094718
New best model found.

Trial 4 of 30
{'tweedie_variance_power': 1.7, 'subsample': 0.8, 'scale_pos_weight': np.float64(0.39740018970423385), 'reg_lambda': 10.0, 'reg_alpha': 1.0, 'min_child_weight': 5, 'max_depth': 8, 'learning_rate': 0.05, 'gamma': 0.5, 'colsample_bytree': 0.6}
Validation RMSE: 166133.618369
Validation MAE: 26844.246540
Validation R²: 0.091570

Trial 5 of 30
{'tweedie_variance_power': 1.7, 'subsample': 0.6, 'scale_pos_weight': np.float64(0.7948003794084677), 'reg_lambda': 2.0, 'reg_alpha': 1.0, 'min_child_weight': 10, 'max_depth': 6, 'learning_rate': 0.01, 'gamma': 0.1, 'colsample_bytree': 0.6}
Validation RMSE: 165601.749505
Validation MAE: 28580.128423
Validation R²: 0.097377
New best model found.

Trial 6 of 30
{'tweedie_variance_power': 1.1, 'subsample': 0.6, 'scale_pos_weight': 1.0, 'reg_lambda': 5.0, 'reg_alpha': 0.0, 'min_child_weight': 5, 'max_depth': 6, 'learning_rate': 0.05, 'gamma': 1.0, 'colsample_bytree': 0.8}
Validation RMSE: 166535.981156
Validation MAE: 30172.869022
Validation R²: 0.087165

Trial 7 of 30
{'tweedie_variance_power': 1.5, 'subsample': 0.6, 'scale_pos_weight': 1.0, 'reg_lambda': 1.0, 'reg_alpha': 0.1, 'min_child_weight': 100, 'max_depth': 8, 'learning_rate': 0.03, 'gamma': 1.0, 'colsample_bytree': 1.0}
Validation RMSE: 165443.402537
Validation MAE: 28281.840725
Validation R²: 0.099103
New best model found.

Trial 8 of 30
{'tweedie_variance_power': 1.5, 'subsample': 1.0, 'scale_pos_weight': np.float64(0.7948003794084677), 'reg_lambda': 5.0, 'reg_alpha': 0.01, 'min_child_weight': 100, 'max_depth': 6, 'learning_rate': 0.03, 'gamma': 0.1, 'colsample_bytree': 0.6}
Validation RMSE: 165505.745388
Validation MAE: 29015.345105
Validation R²: 0.098424

Trial 9 of 30
{'tweedie_variance_power': 1.1, 'subsample': 0.8, 'scale_pos_weight': np.float64(0.7948003794084677), 'reg_lambda': 10.0, 'reg_alpha': 0.0, 'min_child_weight': 50, 'max_depth': 6, 'learning_rate': 0.03, 'gamma': 0.5, 'colsample_bytree': 1.0}
Validation RMSE: 165841.673134
Validation MAE: 29096.116969
Validation R²: 0.094760

Trial 10 of 30
{'tweedie_variance_power': 1.9, 'subsample': 0.6, 'scale_pos_weight': np.float64(0.39740018970423385), 'reg_lambda': 10.0, 'reg_alpha': 0.1, 'min_child_weight': 10, 'max_depth': 4, 'learning_rate': 0.1, 'gamma': 1.0, 'colsample_bytree': 1.0}
Validation RMSE: 165992.088481
Validation MAE: 28106.108895
Validation R²: 0.093117

Trial 11 of 30
{'tweedie_variance_power': 1.3, 'subsample': 0.8, 'scale_pos_weight': np.float64(0.39740018970423385), 'reg_lambda': 2.0, 'reg_alpha': 0.1, 'min_child_weight': 5, 'max_depth': 3, 'learning_rate': 0.05, 'gamma': 0.1, 'colsample_bytree': 1.0}
Validation RMSE: 166667.725955
Validation MAE: 27862.600622
Validation R²: 0.085720

Trial 12 of 30
{'tweedie_variance_power': 1.7, 'subsample': 0.6, 'scale_pos_weight': 1.0, 'reg_lambda': 0.5, 'reg_alpha': 0.0, 'min_child_weight': 10, 'max_depth': 4, 'learning_rate': 0.1, 'gamma': 0.1, 'colsample_bytree': 0.6}
Validation RMSE: 165520.327337
Validation MAE: 29837.665377
Validation R²: 0.098265

Trial 13 of 30
{'tweedie_variance_power': 1.5, 'subsample': 0.8, 'scale_pos_weight': 1.0, 'reg_lambda': 1.0, 'reg_alpha': 1.0, 'min_child_weight': 10, 'max_depth': 6, 'learning_rate': 0.1, 'gamma': 0.5, 'colsample_bytree': 0.6}
Validation RMSE: 165890.948368
Validation MAE: 29665.867148
Validation R²: 0.094222

Trial 14 of 30
{'tweedie_variance_power': 1.1, 'subsample': 0.8, 'scale_pos_weight': np.float64(0.7948003794084677), 'reg_lambda': 10.0, 'reg_alpha': 0.0, 'min_child_weight': 100, 'max_depth': 6, 'learning_rate': 0.03, 'gamma': 0.0, 'colsample_bytree': 0.6}
Validation RMSE: 165728.268625
Validation MAE: 29103.689618
Validation R²: 0.095998

Trial 15 of 30
{'tweedie_variance_power': 1.1, 'subsample': 1.0, 'scale_pos_weight': np.float64(0.8915157763093526), 'reg_lambda': 10.0, 'reg_alpha': 0.01, 'min_child_weight': 100, 'max_depth': 6, 'learning_rate': 0.03, 'gamma': 1.0, 'colsample_bytree': 0.6}
Validation RMSE: 166205.260214
Validation MAE: 29741.456972
Validation R²: 0.090786

Trial 16 of 30
{'tweedie_variance_power': 1.3, 'subsample': 0.8, 'scale_pos_weight': np.float64(0.39740018970423385), 'reg_lambda': 1.0, 'reg_alpha': 1.0, 'min_child_weight': 20, 'max_depth': 4, 'learning_rate': 0.05, 'gamma': 1.0, 'colsample_bytree': 1.0}
Validation RMSE: 166665.396756
Validation MAE: 28089.652857
Validation R²: 0.085745

Trial 17 of 30
{'tweedie_variance_power': 1.3, 'subsample': 0.6, 'scale_pos_weight': 1.0, 'reg_lambda': 0.5, 'reg_alpha': 0.0, 'min_child_weight': 10, 'max_depth': 8, 'learning_rate': 0.01, 'gamma': 0.0, 'colsample_bytree': 1.0}
Validation RMSE: 165514.484201
Validation MAE: 28577.888995
Validation R²: 0.098328

Trial 18 of 30
{'tweedie_variance_power': 1.9, 'subsample': 0.8, 'scale_pos_weight': 1.0, 'reg_lambda': 1.0, 'reg_alpha': 0.1, 'min_child_weight': 20, 'max_depth': 6, 'learning_rate': 0.03, 'gamma': 1.0, 'colsample_bytree': 0.6}
Validation RMSE: 165503.192863
Validation MAE: 28614.275260
Validation R²: 0.098451

Trial 19 of 30
{'tweedie_variance_power': 1.7, 'subsample': 1.0, 'scale_pos_weight': np.float64(0.39740018970423385), 'reg_lambda': 0.5, 'reg_alpha': 1.0, 'min_child_weight': 100, 'max_depth': 8, 'learning_rate': 0.01, 'gamma': 0.0, 'colsample_bytree': 1.0}
Validation RMSE: 165784.234244
Validation MAE: 26689.136293
Validation R²: 0.095387

Trial 20 of 30
{'tweedie_variance_power': 1.1, 'subsample': 0.8, 'scale_pos_weight': np.float64(0.39740018970423385), 'reg_lambda': 2.0, 'reg_alpha': 0.0, 'min_child_weight': 10, 'max_depth': 4, 'learning_rate': 0.01, 'gamma': 0.1, 'colsample_bytree': 0.6}
Validation RMSE: 166056.455539
Validation MAE: 27937.740526
Validation R²: 0.092414

Trial 21 of 30
{'tweedie_variance_power': 1.9, 'subsample': 0.8, 'scale_pos_weight': np.float64(0.39740018970423385), 'reg_lambda': 10.0, 'reg_alpha': 1.0, 'min_child_weight': 50, 'max_depth': 6, 'learning_rate': 0.1, 'gamma': 0.1, 'colsample_bytree': 0.6}
Validation RMSE: 165992.387897
Validation MAE: 27340.658420
Validation R²: 0.093114

Trial 22 of 30
{'tweedie_variance_power': 1.3, 'subsample': 0.8, 'scale_pos_weight': np.float64(0.39740018970423385), 'reg_lambda': 0.5, 'reg_alpha': 0.1, 'min_child_weight': 100, 'max_depth': 3, 'learning_rate': 0.03, 'gamma': 0.5, 'colsample_bytree': 1.0}
Validation RMSE: 166609.658750
Validation MAE: 28036.437543
Validation R²: 0.086357

Trial 23 of 30
{'tweedie_variance_power': 1.5, 'subsample': 0.8, 'scale_pos_weight': np.float64(0.7948003794084677), 'reg_lambda': 5.0, 'reg_alpha': 0.0, 'min_child_weight': 5, 'max_depth': 4, 'learning_rate': 0.01, 'gamma': 0.1, 'colsample_bytree': 0.8}
Validation RMSE: 165891.054199
Validation MAE: 29327.454418
Validation R²: 0.094221

Trial 24 of 30
{'tweedie_variance_power': 1.1, 'subsample': 0.6, 'scale_pos_weight': 1.0, 'reg_lambda': 10.0, 'reg_alpha': 0.0, 'min_child_weight': 100, 'max_depth': 3, 'learning_rate': 0.05, 'gamma': 0.1, 'colsample_bytree': 1.0}
Validation RMSE: 167620.674891
Validation MAE: 29872.396437
Validation R²: 0.075235

Trial 25 of 30
{'tweedie_variance_power': 1.1, 'subsample': 1.0, 'scale_pos_weight': 1.0, 'reg_lambda': 2.0, 'reg_alpha': 0.1, 'min_child_weight': 5, 'max_depth': 6, 'learning_rate': 0.05, 'gamma': 0.1, 'colsample_bytree': 0.6}
Validation RMSE: 166255.744733
Validation MAE: 30066.322870
Validation R²: 0.090234

Trial 26 of 30
{'tweedie_variance_power': 1.3, 'subsample': 0.6, 'scale_pos_weight': np.float64(0.39740018970423385), 'reg_lambda': 5.0, 'reg_alpha': 0.1, 'min_child_weight': 5, 'max_depth': 4, 'learning_rate': 0.1, 'gamma': 0.5, 'colsample_bytree': 0.8}
Validation RMSE: 166513.158887
Validation MAE: 28262.379518
Validation R²: 0.087415

Trial 27 of 30
{'tweedie_variance_power': 1.1, 'subsample': 1.0, 'scale_pos_weight': np.float64(0.7948003794084677), 'reg_lambda': 5.0, 'reg_alpha': 0.0, 'min_child_weight': 100, 'max_depth': 8, 'learning_rate': 0.03, 'gamma': 0.1, 'colsample_bytree': 0.8}
Validation RMSE: 166256.252036
Validation MAE: 28905.519812
Validation R²: 0.090228

Trial 28 of 30
{'tweedie_variance_power': 1.7, 'subsample': 0.8, 'scale_pos_weight': np.float64(0.8915157763093526), 'reg_lambda': 2.0, 'reg_alpha': 0.0, 'min_child_weight': 5, 'max_depth': 3, 'learning_rate': 0.1, 'gamma': 0.5, 'colsample_bytree': 0.8}
Validation RMSE: 166292.640409
Validation MAE: 29804.067286
Validation R²: 0.089830

Trial 29 of 30
{'tweedie_variance_power': 1.1, 'subsample': 1.0, 'scale_pos_weight': np.float64(0.8915157763093526), 'reg_lambda': 0.5, 'reg_alpha': 1.0, 'min_child_weight': 100, 'max_depth': 6, 'learning_rate': 0.05, 'gamma': 0.0, 'colsample_bytree': 0.6}
Validation RMSE: 166232.401582
Validation MAE: 29802.967800
Validation R²: 0.090490

Trial 30 of 30
{'tweedie_variance_power': 1.9, 'subsample': 0.8, 'scale_pos_weight': np.float64(0.7948003794084677), 'reg_lambda': 0.5, 'reg_alpha': 0.1, 'min_child_weight': 5, 'max_depth': 6, 'learning_rate': 0.1, 'gamma': 0.0, 'colsample_bytree': 0.6}
Validation RMSE: 165685.160275
Validation MAE: 28591.074528
Validation R²: 0.096468

Top tuning results:

,trial,validation_rmse,validation_mae,validation_r2,event_best_iteration,size_best_iteration,tweedie_variance_power,subsample,scale_pos_weight,reg_lambda,reg_alpha,min_child_weight,max_depth,learning_rate,gamma,colsample_bytree
0,7,"165,443.40254","28,281.84073",0.09910,326,124,1.50000,0.60000,1.00000,1.00000,0.10000,100,8,0.03000,1.00000,1.00000
1,18,"165,503.19286","28,614.27526",0.09845,409,132,1.90000,0.80000,1.00000,1.00000,0.10000,20,6,0.03000,1.00000,0.60000
2,8,"165,505.74539","29,015.34511",0.09842,572,140,1.50000,1.00000,0.79480,5.00000,0.01000,100,6,0.03000,0.10000,0.60000
3,17,"165,514.48420","28,577.88899",0.09833,716,440,1.30000,0.60000,1.00000,0.50000,0.00000,10,8,0.01000,0.00000,1.00000
4,12,"165,520.32734","29,837.66538",0.09826,161,79,1.70000,0.60000,1.00000,0.50000,0.00000,10,4,0.10000,0.10000,0.60000
5,5,"165,601.74951","28,580.12842",0.09738,998,366,1.70000,0.60000,0.79480,2.00000,1.00000,10,6,0.01000,0.10000,0.60000
6,30,"165,685.16028","28,591.07453",0.09647,118,34,1.90000,0.80000,0.79480,0.50000,0.10000,5,6,0.10000,0.00000,0.60000
7,14,"165,728.26862","29,103.68962",0.09600,568,216,1.10000,0.80000,0.79480,10.00000,0.00000,100,6,0.03000,0.00000,0.60000
8,19,"165,784.23424","26,689.13629",0.09539,955,298,1.70000,1.00000,0.39740,0.50000,1.00000,100,8,0.01000,0.00000,1.00000
9,9,"165,841.67313","29,096.11697",0.09476,490,212,1.10000,0.80000,0.79480,10.00000,0.00000,50,6,0.03000,0.50000,1.00000

Best validation RMSE: 165443.40253672152

Best parameters:
{'tweedie_variance_power': 1.5, 'subsample': 0.6, 'scale_pos_weight': 1.0, 'reg_lambda': 1.0, 'reg_alpha': 0.1, 'min_child_weight': 100, 'max_depth': 8, 'learning_rate': 0.03, 'gamma': 1.0, 'colsample_bytree': 1.0}

Final selected XGBoost model
Validation RMSE: 165443.402537
Validation MAE: 28281.840725
Validation R²: 0.099103

Test RMSE: 484288.138532
Test MAE: 50304.559764
Test R²: 0.034868
CPU times: total: 4h 36min 37s
Wall time: 42min 24s

### Model 2: Tweedie Regression

In [5]:
%%time

from sklearn.linear_model import TweedieRegressor

# ============================================================
# 1. Configuration
# ============================================================

TWEDIE_MAX_ITER = 500
TWEDIE_TOL = 1e-5

# ============================================================
# 2. Hyperparameter grid
# ============================================================

tweedie_param_grid = {
    "power": [1.1,1.3,1.5,1.7,1.9], # Compound Poisson-Gamma range
    "alpha": [0.0,0.0001,0.001,0.01,0.1,1.0,10.0]} # L2 regularisation strength

tweedie_parameter_trials = list(ParameterGrid(tweedie_param_grid))

print("Number of tuning trials:",len(tweedie_parameter_trials))

# ============================================================
# 3. Storage for tuning results
# ============================================================

tweedie_tuning_results = []

# Selectionis based on RMSE
tweedie_best_val_rmse = np.inf
tweedie_best_model = None
tweedie_best_params = None
tweedie_best_val_pred = None

# ============================================================
# 4. Exhaustive grid search
# ============================================================

for trial_number, params in enumerate(tweedie_parameter_trials,start=1):

    print(f"\nTrial {trial_number} "f"of {len(tweedie_parameter_trials)}")
    print(params)

    # --------------------------------------------------------
    # 4A. Train candidate model
    # --------------------------------------------------------

    candidate_model = TweedieRegressor(power=params["power"],
                                       alpha=params["alpha"],
                                       link="log",
                                       solver="newton-cholesky",
                                       max_iter=TWEDIE_MAX_ITER,
                                       tol=TWEDIE_TOL,
                                       fit_intercept=True,
                                       verbose=0)

    try:
        candidate_model.fit(X_train_tabular,y_train.astype(np.float64))

        # ----------------------------------------------------
        # 4B. Validation predictions
        # ----------------------------------------------------

        candidate_val_pred = np.clip(candidate_model.predict(X_val_tabular),0,None)
        candidate_val_pred = np.asarray(candidate_val_pred,dtype=np.float64).reshape(-1)

        # ----------------------------------------------------
        # 4C. Calculate validation metrics
        # ----------------------------------------------------

        candidate_val_rmse = np.sqrt(mean_squared_error(y_val,candidate_val_pred))
        candidate_val_mae = mean_absolute_error(y_val,candidate_val_pred)
        candidate_val_r2 = r2_score(y_val,candidate_val_pred)
        candidate_val_tweedie_deviance = (mean_tweedie_deviance(y_val,candidate_val_pred,power=params["power"]))

        trial_result = {"trial": trial_number,
                        "validation_rmse": candidate_val_rmse,
                        "validation_mae": candidate_val_mae,
                        "validation_r2": candidate_val_r2,
                        "validation_tweedie_deviance": (candidate_val_tweedie_deviance),
                        "iterations_used": (candidate_model.n_iter_),
                        **params}

        tweedie_tuning_results.append(trial_result)

        print(f"Validation RMSE: "f"{candidate_val_rmse:.6f}")
        print(f"Validation MAE: "f"{candidate_val_mae:.6f}")
        print(f"Validation R²: "f"{candidate_val_r2:.6f}")
        print(f"Iterations: "f"{candidate_model.n_iter_}")

        # ----------------------------------------------------
        # 4D. Retain best model by validation RMSE
        # ----------------------------------------------------

        if candidate_val_rmse < tweedie_best_val_rmse:

            if tweedie_best_model is not None:
                del tweedie_best_model

            tweedie_best_val_rmse = (candidate_val_rmse)
            tweedie_best_model = (candidate_model)
            tweedie_best_params = (params.copy())
            tweedie_best_val_pred = (candidate_val_pred.copy())
            print("New best model found.")

        else:
            del candidate_model

    gc.collect()


# ============================================================
# 5. Create tuning-results table
# ============================================================

tweedie_tuning_results_df = pd.DataFrame(tweedie_tuning_results).sort_values("validation_rmse",ascending=True).reset_index(drop=True)

print("\nTop Tweedie tuning results:")
display(tweedie_tuning_results_df.head(10))
print("\nBest validation RMSE:",tweedie_best_val_rmse)
print("\nBest parameters:")
print(tweedie_best_params)

# ============================================================
# 6. Name final selected model
# ============================================================

tweedie_model = (tweedie_best_model)
tweedie_val_pred = (tweedie_best_val_pred)

# ============================================================
# 7. Generate untouched test predictions
# ============================================================

tweedie_test_pred = np.clip(tweedie_model.predict(X_test_tabular),0,None)
tweedie_test_pred = np.asarray(tweedie_test_pred,dtype=np.float64).reshape(-1)

# ============================================================
# 8. Final validation metrics
# ============================================================

tweedie_final_val_rmse = np.sqrt(mean_squared_error(y_val,tweedie_val_pred))
tweedie_final_val_mae = mean_absolute_error(y_val,tweedie_val_pred)
tweedie_final_val_r2 = r2_score(y_val,tweedie_val_pred)

# ============================================================
# 9. Final test metrics
# ============================================================

tweedie_final_test_rmse = np.sqrt(mean_squared_error(y_test,tweedie_test_pred))
tweedie_final_test_mae = mean_absolute_error(y_test,tweedie_test_pred)
tweedie_final_test_r2 = r2_score(y_test,tweedie_test_pred)

print("\nFinal selected Tweedie Regression")
print(f"Validation RMSE: "f"{tweedie_final_val_rmse:.6f}")
print(f"Validation MAE: "f"{tweedie_final_val_mae:.6f}")
print(f"Validation R²: "f"{tweedie_final_val_r2:.6f}")
print(f"\nTest RMSE: "f"{tweedie_final_test_rmse:.6f}")
print(f"Test MAE: "f"{tweedie_final_test_mae:.6f}")
print(f"Test R²: "f"{tweedie_final_test_r2:.6f}"
     )

Number of tuning trials: 35

Trial 1 of 35
{'alpha': 0.0, 'power': 1.1}
Validation RMSE: 171795.693944
Validation MAE: 32296.858647
Validation R²: 0.028594
Iterations: 10
New best model found.

Trial 2 of 35
{'alpha': 0.0, 'power': 1.3}
Validation RMSE: 172178.637892
Validation MAE: 31950.270669
Validation R²: 0.024258
Iterations: 9

Trial 3 of 35
{'alpha': 0.0, 'power': 1.5}
Validation RMSE: 175670.000404
Validation MAE: 31966.511755
Validation R²: -0.015714
Iterations: 8

Trial 4 of 35
{'alpha': 0.0, 'power': 1.7}
Validation RMSE: 194306.510981
Validation MAE: 33041.413599
Validation R²: -0.242656
Iterations: 7

Trial 5 of 35
{'alpha': 0.0, 'power': 1.9}
Validation RMSE: 371486.959608
Validation MAE: 38641.704241
Validation R²: -3.542171
Iterations: 9

Trial 6 of 35
{'alpha': 0.0001, 'power': 1.1}
Validation RMSE: 171795.693253
Validation MAE: 32296.853959
Validation R²: 0.028594
Iterations: 10
New best model found.

Trial 7 of 35
{'alpha': 0.0001, 'power': 1.3}
Validation RMSE: 172178.605671
Validation MAE: 31950.240216
Validation R²: 0.024259
Iterations: 9

Trial 8 of 35
{'alpha': 0.0001, 'power': 1.5}
Validation RMSE: 175669.546637
Validation MAE: 31966.282658
Validation R²: -0.015709
Iterations: 7

Trial 9 of 35
{'alpha': 0.0001, 'power': 1.7}
Validation RMSE: 194288.432773
Validation MAE: 33037.936528
Validation R²: -0.242425
Iterations: 7

Trial 10 of 35
{'alpha': 0.0001, 'power': 1.9}
Validation RMSE: 370248.096613
Validation MAE: 38580.652878
Validation R²: -3.511927
Iterations: 9

Trial 11 of 35
{'alpha': 0.001, 'power': 1.1}
Validation RMSE: 171795.683510
Validation MAE: 32296.809909
Validation R²: 0.028594
Iterations: 9
New best model found.

Trial 12 of 35
{'alpha': 0.001, 'power': 1.3}
Validation RMSE: 172178.189709
Validation MAE: 31949.886809
Validation R²: 0.024263
Iterations: 8

Trial 13 of 35
{'alpha': 0.001, 'power': 1.5}
Validation RMSE: 175661.952921
Validation MAE: 31962.603491
Validation R²: -0.015621
Iterations: 6

Trial 14 of 35
{'alpha': 0.001, 'power': 1.7}
Validation RMSE: 194059.707923
Validation MAE: 32995.968834
Validation R²: -0.239502
Iterations: 7

Trial 15 of 35
{'alpha': 0.001, 'power': 1.9}
Validation RMSE: 358370.216951
Validation MAE: 38002.784957
Validation R²: -3.227077
Iterations: 9

Trial 16 of 35
{'alpha': 0.01, 'power': 1.1}
Validation RMSE: 171795.390891
Validation MAE: 32296.274047
Validation R²: 0.028597
Iterations: 9
New best model found.

Trial 17 of 35
{'alpha': 0.01, 'power': 1.3}
Validation RMSE: 172171.841431
Validation MAE: 31944.905113
Validation R²: 0.024335
Iterations: 7

Trial 18 of 35
{'alpha': 0.01, 'power': 1.5}
Validation RMSE: 175577.078939
Validation MAE: 31921.474932
Validation R²: -0.014640
Iterations: 6

Trial 19 of 35
{'alpha': 0.01, 'power': 1.7}
Validation RMSE: 191976.246500
Validation MAE: 32617.298947
Validation R²: -0.213029
Iterations: 7

Trial 20 of 35
{'alpha': 0.01, 'power': 1.9}
Validation RMSE: 295635.033803
Validation MAE: 34760.265058
Validation R²: -1.876657
Iterations: 9

Trial 21 of 35
{'alpha': 0.1, 'power': 1.1}
Validation RMSE: 171786.998400
Validation MAE: 32289.499756
Validation R²: 0.028692
Iterations: 9
New best model found.

Trial 22 of 35
{'alpha': 0.1, 'power': 1.3}
Validation RMSE: 172105.893380
Validation MAE: 31895.339407
Validation R²: 0.025083
Iterations: 6

Trial 23 of 35
{'alpha': 0.1, 'power': 1.5}
Validation RMSE: 174899.212541
Validation MAE: 31590.212821
Validation R²: -0.006821
Iterations: 6

Trial 24 of 35
{'alpha': 0.1, 'power': 1.7}
Validation RMSE: 181929.946222
Validation MAE: 30620.883283
Validation R²: -0.089393
Iterations: 7

Trial 25 of 35
{'alpha': 0.1, 'power': 1.9}
Validation RMSE: 200476.652978
Validation MAE: 29330.953480
Validation R²: -0.322830
Iterations: 8

Trial 26 of 35
{'alpha': 1.0, 'power': 1.1}
Validation RMSE: 171699.865100
Validation MAE: 32226.171282
Validation R²: 0.029677
Iterations: 9
New best model found.

Trial 27 of 35
{'alpha': 1.0, 'power': 1.3}
Validation RMSE: 171707.451808
Validation MAE: 31563.539716
Validation R²: 0.029591
Iterations: 6

Trial 28 of 35
{'alpha': 1.0, 'power': 1.5}
Validation RMSE: 171955.148481
Validation MAE: 29989.806329
Validation R²: 0.026790
Iterations: 6

Trial 29 of 35
{'alpha': 1.0, 'power': 1.7}
Validation RMSE: 172213.969844
Validation MAE: 27757.276429
Validation R²: 0.023858
Iterations: 7

Trial 30 of 35
{'alpha': 1.0, 'power': 1.9}
Validation RMSE: 171565.832019
Validation MAE: 27053.114007
Validation R²: 0.031191
Iterations: 7
New best model found.

Trial 31 of 35
{'alpha': 10.0, 'power': 1.1}
Validation RMSE: 171324.519733
Validation MAE: 31889.563604
Validation R²: 0.033915
Iterations: 8
New best model found.

Trial 32 of 35
{'alpha': 10.0, 'power': 1.3}
Validation RMSE: 170227.154774
Validation MAE: 30163.866234
Validation R²: 0.046251
Iterations: 6
New best model found.

Trial 33 of 35
{'alpha': 10.0, 'power': 1.5}
Validation RMSE: 169631.696712
Validation MAE: 27770.830997
Validation R²: 0.052912
Iterations: 6
New best model found.

Trial 34 of 35
{'alpha': 10.0, 'power': 1.7}
Validation RMSE: 170218.406596
Validation MAE: 27231.551463
Validation R²: 0.046349
Iterations: 6

Trial 35 of 35
{'alpha': 10.0, 'power': 1.9}
Validation RMSE: 171656.564577
Validation MAE: 29305.221691
Validation R²: 0.030166
Iterations: 5

Top Tweedie tuning results:

,trial,validation_rmse,validation_mae,validation_r2,validation_tweedie_deviance,iterations_used,alpha,power
0,33,"169,631.69671","27,770.83100",0.05291,425.93676,6,10.00000,1.50000
1,34,"170,218.40660","27,231.55146",0.04635,86.12418,6,10.00000,1.70000
2,32,"170,227.15477","30,163.86623",0.04625,"2,749.29863",6,10.00000,1.30000
3,31,"171,324.51973","31,889.56360",0.03391,"23,533.33048",8,10.00000,1.10000
4,30,"171,565.83202","27,053.11401",0.03119,30.09786,7,1.00000,1.90000
5,35,"171,656.56458","29,305.22169",0.03017,31.59634,5,10.00000,1.90000
6,26,"171,699.86510","32,226.17128",0.02968,"23,552.49117",9,1.00000,1.10000
7,27,"171,707.45181","31,563.53972",0.02959,"2,696.82455",6,1.00000,1.30000
8,21,"171,786.99840","32,289.49976",0.02869,"23,575.07598",9,0.10000,1.10000
9,16,"171,795.39089","32,296.27405",0.02860,"23,611.58291",9,0.01000,1.10000

Best validation RMSE: 169631.6967120074

Best parameters:
{'alpha': 10.0, 'power': 1.5}

Final selected Tweedie Regression
Validation RMSE: 169631.696712
Validation MAE: 27770.830997
Validation R²: 0.052912

Test RMSE: 487591.053723
Test MAE: 51136.165402
Test R²: 0.021658
CPU times: total: 20min 53s
Wall time: 12min 1s

### Model 3: LSTM

In [6]:
%%time

import tensorflow as tf
from tensorflow.keras import Model
from tensorflow.keras.layers import (Input,LSTM,Dense,Dropout,LayerNormalization,SpatialDropout1D)
from tensorflow.keras.callbacks import (EarlyStopping,ReduceLROnPlateau)
from tensorflow.keras.optimizers import Adam

# Tweedie deviance loss for a given power
def tweedie_deviance_raw(y_true,y_pred,power):
    epsilon = tf.keras.backend.epsilon()
    safe_true = tf.maximum(tf.cast(y_true, tf.float32),0.0)
    safe_prediction = tf.maximum(tf.cast(y_pred, tf.float32),epsilon)
    p = tf.cast(power, tf.float32)
    term_1 = (tf.pow(safe_true, 2.0 - p) / ((1.0 - p) * (2.0 - p)))
    term_2 = (safe_true * tf.pow(safe_prediction, 1.0 - p) / (1.0 - p))
    term_3 = (tf.pow(safe_prediction, 2.0 - p) / (2.0 - p))
    deviance = 2.0 * (term_1 - term_2 + term_3)
    return tf.reduce_mean(deviance)

# ============================================================
# Define LSTM target scaling value
# ============================================================

lstm_positive_training_targets = np.asarray(y_train[y_train > 0],dtype=np.float64)
LSTM_AMOUNT_SCALE = np.quantile(lstm_positive_training_targets,0.95)
if (not np.isfinite(LSTM_AMOUNT_SCALE) or LSTM_AMOUNT_SCALE <= 0): LSTM_AMOUNT_SCALE = 1.0
print("LSTM_AMOUNT_SCALE:",LSTM_AMOUNT_SCALE)

# ============================================================
# Builds a tf.data.Dataset via from_generator
# ============================================================

def build_liquidation_dataset(
    feature_matrix,
    targets,
    endpoint_indices,
    sequence_length,
    number_of_features,
    amount_scale,
    batch_size=512,
    shuffle=False):

    targets = np.asarray(targets)
    endpoint_indices = np.asarray(endpoint_indices, dtype=np.int64)
    sequence_length = int(sequence_length)
    amount_scale = float(amount_scale)
    batch_size = int(batch_size)
    offsets = np.arange(sequence_length - 1,-1,-1,dtype=np.int64)
    
    def generator():
        order = np.arange(len(endpoint_indices))
        if shuffle: np.random.shuffle(order)
        number_of_batches = int(np.ceil(len(order) / batch_size))
        for batch_number in range(number_of_batches):
            start = batch_number * batch_size
            stop = min(start + batch_size, len(order))
            selected_order = order[start:stop]
            batch_endpoints = endpoint_indices[selected_order]
            sequence_indices = (batch_endpoints[:, None] - offsets[None, :])
            X_batch = feature_matrix[sequence_indices].astype("float32")
            y_raw = targets[batch_endpoints].astype("float32")
            event_target = (y_raw > 0).astype("float32").reshape(-1, 1)
            amount_target = ( y_raw / amount_scale).astype("float32").reshape(-1, 1)
            yield X_batch, {"event_output": event_target,"amount_output": amount_target}

    output_signature = (tf.TensorSpec(shape=(None, sequence_length, number_of_features),dtype=tf.float32),
        {"event_output": tf.TensorSpec(shape=(None, 1), dtype=tf.float32),"amount_output": tf.TensorSpec(shape=(None, 1), dtype=tf.float32)})

    dataset = tf.data.Dataset.from_generator(generator,output_signature=output_signature)

    return dataset.prefetch(tf.data.AUTOTUNE)

# ============================================================
# 1. Configuration
# ============================================================

LSTM_TUNING_TRIALS = 15
LSTM_TUNING_EPOCHS = 15
LSTM_BEST_WEIGHTS_PATH = ("best_lstm_tuning.weights.h5")
number_of_sequence_features = (X_sequence_all.shape[1])

# ============================================================
# 2. Hyperparameter search space
# ============================================================

lstm_param_space = {"batch_size": [256,512,1024],
                    "lstm_units_1": [32,64,128],
                    "lstm_units_2": [16,32,64],
                    "dense_units_1": [32,64,128],
                    "dense_units_2": [16,32,64],
                    "spatial_dropout": [0.0,0.10,0.20],
                    "lstm_dropout": [0.10,0.20,0.30],
                    "dense_dropout": [0.10,0.25,0.40],
                    "learning_rate": [0.0001,0.0003,0.001,0.003],
                    "clipnorm": [0.5,1.0,2.0],
                    "amount_loss_weight": [0.5,1.0,2.0,5.0],
                    "tweedie_power": [1.1,1.3,1.5,1.7,1.9]}

lstm_parameter_trials = list(ParameterSampler(lstm_param_space,
                                              n_iter=LSTM_TUNING_TRIALS,
                                              random_state=SEED))

print("Number of LSTM tuning trials:",len(lstm_parameter_trials))

# ============================================================
# 3. Compile the model
# ============================================================

def build_lstm_hurdle_model(params):

    sequence_input = Input(shape=(SEQUENCE_LENGTH,number_of_sequence_features),name="sequence_input")
    x = SpatialDropout1D(rate=params["spatial_dropout"])(sequence_input)
    x = LSTM(units=params["lstm_units_1"],return_sequences=True,name="lstm_1")(x)
    x = Dropout(rate=params["lstm_dropout"])(x)
    x = LSTM(units=params["lstm_units_2"],return_sequences=False,name="lstm_2")(x)
    x = LayerNormalization()(x)
    x = Dense(units=params["dense_units_1"],activation="relu")(x)
    x = Dropout(rate=params["dense_dropout"])(x)
    x = Dense(units=params["dense_units_2"],activation="relu")(x)
    event_output = Dense(units=1,activation="sigmoid",name="event_output")(x)
    amount_output = Dense(units=1,activation="softplus",name="amount_output")(x)
    model = Model(inputs=sequence_input,outputs={"event_output": event_output,"amount_output": amount_output})
    amount_loss_fn = partial(tweedie_deviance_raw,power=params["tweedie_power"])
    amount_loss_fn.__name__ = "tweedie_deviance_raw"  # Keras expects a __name__ attribute

    model.compile(optimizer=Adam(learning_rate=params["learning_rate"],clipnorm=params["clipnorm"]),
        loss={"event_output":"binary_crossentropy","amount_output":amount_loss_fn},
        loss_weights={"event_output": 1.0,"amount_output":params["amount_loss_weight"]},
        metrics={"event_output": [tf.keras.metrics.AUC(curve="PR",name="pr_auc")]})

    return model

# ============================================================
# 4. Prediction function
# ============================================================

def get_lstm_hurdle_prediction(model,sequence,amount_scale,verbose=0):

    outputs = model.predict(sequence,verbose=verbose)
    event_probability = np.asarray(outputs["event_output"],dtype=np.float64).reshape(-1)
    conditional_amount = np.asarray(outputs["amount_output"],dtype=np.float64).reshape(-1)
    conditional_amount = np.clip(conditional_amount * amount_scale,0,None)
    prediction = (event_probability * conditional_amount)
    return np.asarray(prediction,dtype=np.float64).reshape(-1)

# ============================================================
# 5. Tuning results for storage
# ============================================================

lstm_tuning_results = []
lstm_best_val_rmse = np.inf
lstm_best_params = None
lstm_best_val_pred = None
lstm_best_epochs_used = None

# ============================================================
# 6. Random hyperparameter search
# ============================================================

for trial_number, params in enumerate(lstm_parameter_trials,start=1):
    print(f"\nTrial {trial_number} "f"of {LSTM_TUNING_TRIALS}")
    print(params)

    # ============================================================
    # A. Reset TensorFlow state
    # ============================================================

    tf.keras.backend.clear_session()
    random.seed(SEED + trial_number)
    np.random.seed(SEED + trial_number)
    tf.random.set_seed(SEED + trial_number)

    # ============================================================
    # B. Create datasets using candidate batch size
    # ============================================================

    candidate_train_sequence = build_liquidation_dataset(feature_matrix=X_sequence_all,
                                                         targets=y_all,
                                                         endpoint_indices=train_idx,
                                                         sequence_length=SEQUENCE_LENGTH,
                                                         number_of_features=number_of_sequence_features,
                                                         amount_scale=LSTM_AMOUNT_SCALE,
                                                         batch_size=params["batch_size"],
                                                         shuffle=True)
                                                 
    candidate_validation_sequence = build_liquidation_dataset(feature_matrix=X_sequence_all,
                                                              targets=y_all,
                                                              endpoint_indices=val_idx,
                                                              sequence_length=SEQUENCE_LENGTH,
                                                              number_of_features=number_of_sequence_features,
                                                              amount_scale=LSTM_AMOUNT_SCALE,
                                                              batch_size=params["batch_size"],
                                                              shuffle=False)

    # ============================================================
    # C. Build model
    # ============================================================

    candidate_model = (build_lstm_hurdle_model(params))

    # ============================================================
    # D. Train model
    # ============================================================

    candidate_callbacks = [EarlyStopping(monitor="val_loss",mode="min",patience=3,restore_best_weights=True,verbose=1),
                           ReduceLROnPlateau(monitor="val_loss",mode="min",factor=0.5,patience=2,min_lr=1e-5,verbose=1)]

    try:

        candidate_history = (candidate_model.fit(candidate_train_sequence,validation_data=(candidate_validation_sequence),
                epochs=LSTM_TUNING_EPOCHS,callbacks=candidate_callbacks,verbose=1))

    # ============================================================
    # E. Obtain the Validation data predictions
    # ============================================================

        candidate_val_pred = (get_lstm_hurdle_prediction(model=candidate_model,sequence=(candidate_validation_sequence),
                amount_scale=LSTM_AMOUNT_SCALE,verbose=0))

    # ============================================================
    # F. Obtain the Validation data metrics
    # ============================================================

        candidate_val_rmse = np.sqrt(mean_squared_error(y_val,candidate_val_pred))
        candidate_val_mae = (mean_absolute_error(y_val,candidate_val_pred))
        candidate_val_r2 = r2_score(y_val,candidate_val_pred)
        candidate_epochs_used = len(candidate_history.history["loss"])
        candidate_best_val_loss = np.min(candidate_history.history["val_loss"])

        trial_result = {"trial": trial_number,
                        "validation_rmse":candidate_val_rmse,
                        "validation_mae":candidate_val_mae,
                        "validation_r2":candidate_val_r2,
                        "best_validation_loss":candidate_best_val_loss,
                        "epochs_used":candidate_epochs_used,
                        **params}

        lstm_tuning_results.append(trial_result)

        print(f"Validation RMSE: "f"{candidate_val_rmse:.6f}")
        print(f"Validation MAE: "f"{candidate_val_mae:.6f}")
        print(f"Validation R²: "f"{candidate_val_r2:.6f}")

    # ============================================================
    # 6G. Retain best model by validation RMSE
    # ============================================================

        if candidate_val_rmse < lstm_best_val_rmse:
            lstm_best_val_rmse = (candidate_val_rmse)
            lstm_best_params = (params.copy())
            lstm_best_val_pred = (candidate_val_pred.copy())
            lstm_best_epochs_used = (candidate_epochs_used)
            candidate_model.save_weights(LSTM_BEST_WEIGHTS_PATH)
            print("New best LSTM model found.")

    del candidate_model
    del candidate_train_sequence
    del candidate_validation_sequence

    gc.collect()

# ============================================================
# 7. Results table from tuning
# ============================================================

lstm_tuning_results_df = pd.DataFrame(lstm_tuning_results).sort_values("validation_rmse",ascending=True).reset_index(drop=True)

print("\nTop LSTM tuning results:")
display(lstm_tuning_results_df.head(10))
print("\nBest validation RMSE:",lstm_best_val_rmse)
print("\nBest parameters:")
print(lstm_best_params)

# ============================================================
# 8. Rebuild selected model and load its weights
# ============================================================

tf.keras.backend.clear_session()
lstm_model = build_lstm_hurdle_model(lstm_best_params)
lstm_model.load_weights(LSTM_BEST_WEIGHTS_PATH)

# ============================================================
# 9. Recreate selected validation and test datasets
# ============================================================

validation_sequence = build_liquidation_dataset(feature_matrix=X_sequence_all,
                                                targets=y_all,
                                                endpoint_indices=val_idx,
                                                sequence_length=SEQUENCE_LENGTH,
                                                number_of_features=number_of_sequence_features,
                                                amount_scale=LSTM_AMOUNT_SCALE,
                                                batch_size=lstm_best_params["batch_size"],
                                                shuffle=False)

test_sequence = build_liquidation_dataset(feature_matrix=X_sequence_all,
                                          targets=y_all,
                                          endpoint_indices=test_idx,
                                          sequence_length=SEQUENCE_LENGTH,
                                          number_of_features=number_of_sequence_features,
                                          amount_scale=LSTM_AMOUNT_SCALE,
                                          batch_size=lstm_best_params["batch_size"],
                                          shuffle=False)

# ============================================================
# 10. Final validation predictions
# ============================================================

lstm_val_pred = get_lstm_hurdle_prediction(model=lstm_model,sequence=validation_sequence,amount_scale=LSTM_AMOUNT_SCALE,verbose=1)

# ============================================================
# 11. Untouched test predictions
# ============================================================

lstm_test_pred = get_lstm_hurdle_prediction(model=lstm_model,sequence=test_sequence,amount_scale=LSTM_AMOUNT_SCALE,verbose=1)

# ============================================================
# 12. Final metrics
# ============================================================

lstm_final_val_rmse = np.sqrt(mean_squared_error(y_val,lstm_val_pred))
lstm_final_val_mae = mean_absolute_error(y_val,lstm_val_pred)
lstm_final_val_r2 = r2_score(y_val,lstm_val_pred)
lstm_final_test_rmse = np.sqrt(mean_squared_error(y_test,lstm_test_pred))
lstm_final_test_mae = mean_absolute_error(y_test,lstm_test_pred)
lstm_final_test_r2 = r2_score(y_test,lstm_test_pred)

print("\nFinal selected LSTM hurdle model")
print(f"Validation RMSE: "f"{lstm_final_val_rmse:.6f}")
print(f"Validation MAE: "f"{lstm_final_val_mae:.6f}")
print(f"Validation R²: "f"{lstm_final_val_r2:.6f}")
print(f"\nTest RMSE: "f"{lstm_final_test_rmse:.6f}")
print(f"Test MAE: "f"{lstm_final_test_mae:.6f}")
print(f"Test R²: "f"{lstm_final_test_r2:.6f}")

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/attr_value.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/resource_handle.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor_shape.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/types.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/full_type.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/function.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/node_def.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/op_def.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/graph.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/graph_debug_info.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/versions.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/protobuf/config.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at xla/tsl/protobuf/coordination_config.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/cost_graph.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/step_stats.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/allocation_description.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/framework/tensor_description.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/protobuf/cluster.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(
C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\google\protobuf\runtime_version.py:98: UserWarning: Protobuf gencode version 5.28.3 is exactly one major version older than the runtime version 6.31.1 at tensorflow/core/protobuf/debug.proto. Please update the gencode to avoid compatibility violations in the next runtime release.
  warnings.warn(

LSTM_AMOUNT_SCALE: 278722.4046875
Number of LSTM tuning trials: 15

Trial 1 of 15
{'tweedie_power': 1.7, 'spatial_dropout': 0.1, 'lstm_units_2': 16, 'lstm_units_1': 64, 'lstm_dropout': 0.1, 'learning_rate': 0.0003, 'dense_units_2': 16, 'dense_units_1': 64, 'dense_dropout': 0.4, 'clipnorm': 2.0, 'batch_size': 256, 'amount_loss_weight': 0.5}
WARNING:tensorflow:From C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

Epoch 1/15
    814/Unknown 116s 133ms/step - amount_output_loss: 2.7440 - event_output_loss: 0.6390 - event_output_pr_auc: 0.7314 - loss: 2.0110

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\trainers\epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

814/814 ━━━━━━━━━━━━━━━━━━━━ 129s 150ms/step - amount_output_loss: 2.2920 - event_output_loss: 0.6040 - event_output_pr_auc: 0.7720 - loss: 1.7528 - val_amount_output_loss: 1.7536 - val_event_output_loss: 0.5317 - val_event_output_pr_auc: 0.8160 - val_loss: 1.4159 - learning_rate: 3.0000e-04
Epoch 2/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 124s 152ms/step - amount_output_loss: 2.0112 - event_output_loss: 0.5718 - event_output_pr_auc: 0.8025 - loss: 1.5790 - val_amount_output_loss: 1.7158 - val_event_output_loss: 0.5227 - val_event_output_pr_auc: 0.8228 - val_loss: 1.3879 - learning_rate: 3.0000e-04
Epoch 3/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 109s 134ms/step - amount_output_loss: 1.9575 - event_output_loss: 0.5659 - event_output_pr_auc: 0.8095 - loss: 1.5468 - val_amount_output_loss: 1.7351 - val_event_output_loss: 0.5285 - val_event_output_pr_auc: 0.8239 - val_loss: 1.4035 - learning_rate: 3.0000e-04
Epoch 4/15
813/814 ━━━━━━━━━━━━━━━━━━━━ 0s 113ms/step - amount_output_loss: 1.9388 - event_output_loss: 0.5637 - event_output_pr_auc: 0.8115 - loss: 1.5331
Epoch 4: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.
814/814 ━━━━━━━━━━━━━━━━━━━━ 101s 123ms/step - amount_output_loss: 1.9200 - event_output_loss: 0.5630 - event_output_pr_auc: 0.8130 - loss: 1.5245 - val_amount_output_loss: 1.7124 - val_event_output_loss: 0.5262 - val_event_output_pr_auc: 0.8281 - val_loss: 1.3896 - learning_rate: 3.0000e-04
Epoch 5/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 103s 126ms/step - amount_output_loss: 1.8909 - event_output_loss: 0.5602 - event_output_pr_auc: 0.8161 - loss: 1.5077 - val_amount_output_loss: 1.6960 - val_event_output_loss: 0.5229 - val_event_output_pr_auc: 0.8259 - val_loss: 1.3783 - learning_rate: 1.5000e-04
Epoch 6/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 98s 120ms/step - amount_output_loss: 1.8854 - event_output_loss: 0.5582 - event_output_pr_auc: 0.8181 - loss: 1.5020 - val_amount_output_loss: 1.6859 - val_event_output_loss: 0.5213 - val_event_output_pr_auc: 0.8271 - val_loss: 1.3714 - learning_rate: 1.5000e-04
Epoch 7/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 100s 122ms/step - amount_output_loss: 1.8729 - event_output_loss: 0.5573 - event_output_pr_auc: 0.8192 - loss: 1.4952 - val_amount_output_loss: 1.6891 - val_event_output_loss: 0.5214 - val_event_output_pr_auc: 0.8258 - val_loss: 1.3732 - learning_rate: 1.5000e-04
Epoch 8/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 97s 120ms/step - amount_output_loss: 1.8814 - event_output_loss: 0.5567 - event_output_pr_auc: 0.8196 - loss: 1.4991 - val_amount_output_loss: 1.6881 - val_event_output_loss: 0.5199 - val_event_output_pr_auc: 0.8270 - val_loss: 1.3713 - learning_rate: 1.5000e-04
Epoch 9/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 104s 127ms/step - amount_output_loss: 1.8625 - event_output_loss: 0.5544 - event_output_pr_auc: 0.8226 - loss: 1.4881 - val_amount_output_loss: 1.6838 - val_event_output_loss: 0.5187 - val_event_output_pr_auc: 0.8276 - val_loss: 1.3677 - learning_rate: 1.5000e-04
Epoch 10/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 103s 127ms/step - amount_output_loss: 1.8524 - event_output_loss: 0.5547 - event_output_pr_auc: 0.8220 - loss: 1.4828 - val_amount_output_loss: 1.7022 - val_event_output_loss: 0.5201 - val_event_output_pr_auc: 0.8265 - val_loss: 1.3786 - learning_rate: 1.5000e-04
Epoch 11/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 89s 110ms/step - amount_output_loss: 1.8376 - event_output_loss: 0.5540 - event_output_pr_auc: 0.8232 - loss: 1.4739 - val_amount_output_loss: 1.6753 - val_event_output_loss: 0.5195 - val_event_output_pr_auc: 0.8277 - val_loss: 1.3644 - learning_rate: 1.5000e-04
Epoch 12/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 100s 122ms/step - amount_output_loss: 1.8292 - event_output_loss: 0.5530 - event_output_pr_auc: 0.8242 - loss: 1.4696 - val_amount_output_loss: 1.6640 - val_event_output_loss: 0.5186 - val_event_output_pr_auc: 0.8277 - val_loss: 1.3578 - learning_rate: 1.5000e-04
Epoch 13/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 91s 112ms/step - amount_output_loss: 1.8245 - event_output_loss: 0.5513 - event_output_pr_auc: 0.8252 - loss: 1.4650 - val_amount_output_loss: 1.6556 - val_event_output_loss: 0.5156 - val_event_output_pr_auc: 0.8289 - val_loss: 1.3506 - learning_rate: 1.5000e-04
Epoch 14/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 106s 130ms/step - amount_output_loss: 1.8121 - event_output_loss: 0.5508 - event_output_pr_auc: 0.8264 - loss: 1.4582 - val_amount_output_loss: 1.6698 - val_event_output_loss: 0.5198 - val_event_output_pr_auc: 0.8265 - val_loss: 1.3620 - learning_rate: 1.5000e-04
Epoch 15/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step - amount_output_loss: 1.8111 - event_output_loss: 0.5505 - event_output_pr_auc: 0.8270 - loss: 1.4561
Epoch 15: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
814/814 ━━━━━━━━━━━━━━━━━━━━ 103s 126ms/step - amount_output_loss: 1.8039 - event_output_loss: 0.5502 - event_output_pr_auc: 0.8271 - loss: 1.4532 - val_amount_output_loss: 1.6630 - val_event_output_loss: 0.5217 - val_event_output_pr_auc: 0.8268 - val_loss: 1.3604 - learning_rate: 1.5000e-04
Restoring model weights from the end of the best epoch: 13.
Validation RMSE: 167340.983764
Validation MAE: 29550.780757
Validation R²: 0.078318
New best LSTM model found.

Trial 2 of 15
{'tweedie_power': 1.1, 'spatial_dropout': 0.2, 'lstm_units_2': 32, 'lstm_units_1': 64, 'lstm_dropout': 0.1, 'learning_rate': 0.0003, 'dense_units_2': 16, 'dense_units_1': 32, 'dense_dropout': 0.25, 'clipnorm': 0.5, 'batch_size': 1024, 'amount_loss_weight': 1.0}
Epoch 1/15
    204/Unknown 95s 416ms/step - amount_output_loss: 0.9029 - event_output_loss: 0.6865 - event_output_pr_auc: 0.6273 - loss: 1.5895

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\trainers\epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

204/204 ━━━━━━━━━━━━━━━━━━━━ 102s 451ms/step - amount_output_loss: 0.6506 - event_output_loss: 0.6486 - event_output_pr_auc: 0.6920 - loss: 1.3066 - val_amount_output_loss: 0.3016 - val_event_output_loss: 0.5392 - val_event_output_pr_auc: 0.8035 - val_loss: 0.8603 - learning_rate: 3.0000e-04
Epoch 2/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 92s 452ms/step - amount_output_loss: 0.4978 - event_output_loss: 0.5867 - event_output_pr_auc: 0.7797 - loss: 1.0891 - val_amount_output_loss: 0.2933 - val_event_output_loss: 0.5248 - val_event_output_pr_auc: 0.8134 - val_loss: 0.8369 - learning_rate: 3.0000e-04
Epoch 3/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 113s 553ms/step - amount_output_loss: 0.4783 - event_output_loss: 0.5764 - event_output_pr_auc: 0.7931 - loss: 1.0580 - val_amount_output_loss: 0.2903 - val_event_output_loss: 0.5217 - val_event_output_pr_auc: 0.8178 - val_loss: 0.8306 - learning_rate: 3.0000e-04
Epoch 4/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 86s 418ms/step - amount_output_loss: 0.4677 - event_output_loss: 0.5705 - event_output_pr_auc: 0.7995 - loss: 1.0427 - val_amount_output_loss: 0.2859 - val_event_output_loss: 0.5193 - val_event_output_pr_auc: 0.8212 - val_loss: 0.8236 - learning_rate: 3.0000e-04
Epoch 5/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 82s 401ms/step - amount_output_loss: 0.4550 - event_output_loss: 0.5679 - event_output_pr_auc: 0.8037 - loss: 1.0288 - val_amount_output_loss: 0.2836 - val_event_output_loss: 0.5171 - val_event_output_pr_auc: 0.8227 - val_loss: 0.8189 - learning_rate: 3.0000e-04
Epoch 6/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 77s 378ms/step - amount_output_loss: 0.4494 - event_output_loss: 0.5656 - event_output_pr_auc: 0.8072 - loss: 1.0206 - val_amount_output_loss: 0.2839 - val_event_output_loss: 0.5144 - val_event_output_pr_auc: 0.8237 - val_loss: 0.8166 - learning_rate: 3.0000e-04
Epoch 7/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 80s 394ms/step - amount_output_loss: 0.4490 - event_output_loss: 0.5637 - event_output_pr_auc: 0.8103 - loss: 1.0178 - val_amount_output_loss: 0.2838 - val_event_output_loss: 0.5133 - val_event_output_pr_auc: 0.8252 - val_loss: 0.8153 - learning_rate: 3.0000e-04
Epoch 8/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 77s 377ms/step - amount_output_loss: 0.4400 - event_output_loss: 0.5622 - event_output_pr_auc: 0.8121 - loss: 1.0078 - val_amount_output_loss: 0.2829 - val_event_output_loss: 0.5145 - val_event_output_pr_auc: 0.8242 - val_loss: 0.8157 - learning_rate: 3.0000e-04
Epoch 9/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 0s 361ms/step - amount_output_loss: 0.4175 - event_output_loss: 0.5628 - event_output_pr_auc: 0.8140 - loss: 0.9803
Epoch 9: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.
204/204 ━━━━━━━━━━━━━━━━━━━━ 82s 401ms/step - amount_output_loss: 0.4341 - event_output_loss: 0.5606 - event_output_pr_auc: 0.8145 - loss: 0.9999 - val_amount_output_loss: 0.2891 - val_event_output_loss: 0.5117 - val_event_output_pr_auc: 0.8254 - val_loss: 0.8192 - learning_rate: 3.0000e-04
Epoch 10/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 82s 401ms/step - amount_output_loss: 0.4289 - event_output_loss: 0.5595 - event_output_pr_auc: 0.8155 - loss: 0.9934 - val_amount_output_loss: 0.2830 - val_event_output_loss: 0.5125 - val_event_output_pr_auc: 0.8253 - val_loss: 0.8138 - learning_rate: 1.5000e-04
Epoch 11/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 76s 375ms/step - amount_output_loss: 0.4364 - event_output_loss: 0.5601 - event_output_pr_auc: 0.8146 - loss: 1.0023 - val_amount_output_loss: 0.2865 - val_event_output_loss: 0.5121 - val_event_output_pr_auc: 0.8251 - val_loss: 0.8169 - learning_rate: 1.5000e-04
Epoch 12/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 0s 419ms/step - amount_output_loss: 0.4394 - event_output_loss: 0.5613 - event_output_pr_auc: 0.8167 - loss: 1.0007
Epoch 12: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
204/204 ━━━━━━━━━━━━━━━━━━━━ 92s 453ms/step - amount_output_loss: 0.4262 - event_output_loss: 0.5589 - event_output_pr_auc: 0.8167 - loss: 0.9905 - val_amount_output_loss: 0.2858 - val_event_output_loss: 0.5116 - val_event_output_pr_auc: 0.8256 - val_loss: 0.8157 - learning_rate: 1.5000e-04
Epoch 13/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 89s 433ms/step - amount_output_loss: 0.4259 - event_output_loss: 0.5585 - event_output_pr_auc: 0.8169 - loss: 0.9892 - val_amount_output_loss: 0.2830 - val_event_output_loss: 0.5121 - val_event_output_pr_auc: 0.8254 - val_loss: 0.8134 - learning_rate: 7.5000e-05
Epoch 14/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 87s 426ms/step - amount_output_loss: 0.4258 - event_output_loss: 0.5580 - event_output_pr_auc: 0.8178 - loss: 0.9883 - val_amount_output_loss: 0.2842 - val_event_output_loss: 0.5132 - val_event_output_pr_auc: 0.8255 - val_loss: 0.8157 - learning_rate: 7.5000e-05
Epoch 15/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 0s 341ms/step - amount_output_loss: 0.4155 - event_output_loss: 0.5614 - event_output_pr_auc: 0.8180 - loss: 0.9769
Epoch 15: ReduceLROnPlateau reducing learning rate to 3.7500001781154424e-05.
204/204 ━━━━━━━━━━━━━━━━━━━━ 77s 378ms/step - amount_output_loss: 0.4193 - event_output_loss: 0.5580 - event_output_pr_auc: 0.8177 - loss: 0.9826 - val_amount_output_loss: 0.2844 - val_event_output_loss: 0.5127 - val_event_output_pr_auc: 0.8256 - val_loss: 0.8154 - learning_rate: 7.5000e-05
Restoring model weights from the end of the best epoch: 13.
Validation RMSE: 167475.934710
Validation MAE: 29109.700994
Validation R²: 0.076831

Trial 3 of 15
{'tweedie_power': 1.5, 'spatial_dropout': 0.1, 'lstm_units_2': 64, 'lstm_units_1': 32, 'lstm_dropout': 0.3, 'learning_rate': 0.0003, 'dense_units_2': 16, 'dense_units_1': 32, 'dense_dropout': 0.1, 'clipnorm': 0.5, 'batch_size': 512, 'amount_loss_weight': 0.5}
Epoch 1/15
    407/Unknown 91s 207ms/step - amount_output_loss: 1.2715 - event_output_loss: 0.6391 - event_output_pr_auc: 0.7238 - loss: 1.2749

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\trainers\epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

407/407 ━━━━━━━━━━━━━━━━━━━━ 100s 229ms/step - amount_output_loss: 1.0954 - event_output_loss: 0.6027 - event_output_pr_auc: 0.7704 - loss: 1.1535 - val_amount_output_loss: 0.7434 - val_event_output_loss: 0.5344 - val_event_output_pr_auc: 0.8143 - val_loss: 0.9156 - learning_rate: 3.0000e-04
Epoch 2/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 96s 237ms/step - amount_output_loss: 0.9382 - event_output_loss: 0.5684 - event_output_pr_auc: 0.8078 - loss: 1.0399 - val_amount_output_loss: 0.7179 - val_event_output_loss: 0.5263 - val_event_output_pr_auc: 0.8214 - val_loss: 0.8948 - learning_rate: 3.0000e-04
Epoch 3/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 90s 220ms/step - amount_output_loss: 0.9162 - event_output_loss: 0.5627 - event_output_pr_auc: 0.8141 - loss: 1.0234 - val_amount_output_loss: 0.7227 - val_event_output_loss: 0.5253 - val_event_output_pr_auc: 0.8239 - val_loss: 0.8962 - learning_rate: 3.0000e-04
Epoch 4/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 98s 240ms/step - amount_output_loss: 0.8992 - event_output_loss: 0.5594 - event_output_pr_auc: 0.8179 - loss: 1.0114 - val_amount_output_loss: 0.7098 - val_event_output_loss: 0.5196 - val_event_output_pr_auc: 0.8258 - val_loss: 0.8839 - learning_rate: 3.0000e-04
Epoch 5/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 77s 190ms/step - amount_output_loss: 0.8916 - event_output_loss: 0.5563 - event_output_pr_auc: 0.8214 - loss: 1.0047 - val_amount_output_loss: 0.7175 - val_event_output_loss: 0.5185 - val_event_output_pr_auc: 0.8228 - val_loss: 0.8866 - learning_rate: 3.0000e-04
Epoch 6/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 111s 273ms/step - amount_output_loss: 0.8874 - event_output_loss: 0.5533 - event_output_pr_auc: 0.8246 - loss: 0.9994 - val_amount_output_loss: 0.7030 - val_event_output_loss: 0.5219 - val_event_output_pr_auc: 0.8219 - val_loss: 0.8829 - learning_rate: 3.0000e-04
Epoch 7/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 130s 318ms/step - amount_output_loss: 0.8778 - event_output_loss: 0.5521 - event_output_pr_auc: 0.8262 - loss: 0.9935 - val_amount_output_loss: 0.7072 - val_event_output_loss: 0.5184 - val_event_output_pr_auc: 0.8219 - val_loss: 0.8813 - learning_rate: 3.0000e-04
Epoch 8/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 122s 299ms/step - amount_output_loss: 0.8718 - event_output_loss: 0.5505 - event_output_pr_auc: 0.8279 - loss: 0.9881 - val_amount_output_loss: 0.7091 - val_event_output_loss: 0.5198 - val_event_output_pr_auc: 0.8261 - val_loss: 0.8836 - learning_rate: 3.0000e-04
Epoch 9/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 110s 270ms/step - amount_output_loss: 0.8638 - event_output_loss: 0.5482 - event_output_pr_auc: 0.8301 - loss: 0.9826 - val_amount_output_loss: 0.6995 - val_event_output_loss: 0.5217 - val_event_output_pr_auc: 0.8219 - val_loss: 0.8808 - learning_rate: 3.0000e-04
Epoch 10/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 114s 201ms/step - amount_output_loss: 0.8631 - event_output_loss: 0.5469 - event_output_pr_auc: 0.8314 - loss: 0.9810 - val_amount_output_loss: 0.7002 - val_event_output_loss: 0.5197 - val_event_output_pr_auc: 0.8225 - val_loss: 0.8789 - learning_rate: 3.0000e-04
Epoch 11/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 106s 261ms/step - amount_output_loss: 0.8531 - event_output_loss: 0.5465 - event_output_pr_auc: 0.8317 - loss: 0.9755 - val_amount_output_loss: 0.7045 - val_event_output_loss: 0.5192 - val_event_output_pr_auc: 0.8213 - val_loss: 0.8807 - learning_rate: 3.0000e-04
Epoch 12/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 84s 206ms/step - amount_output_loss: 0.8453 - event_output_loss: 0.5455 - event_output_pr_auc: 0.8325 - loss: 0.9706 - val_amount_output_loss: 0.6946 - val_event_output_loss: 0.5182 - val_event_output_pr_auc: 0.8260 - val_loss: 0.8747 - learning_rate: 3.0000e-04
Epoch 13/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 87s 213ms/step - amount_output_loss: 0.8423 - event_output_loss: 0.5438 - event_output_pr_auc: 0.8340 - loss: 0.9675 - val_amount_output_loss: 0.7094 - val_event_output_loss: 0.5133 - val_event_output_pr_auc: 0.8283 - val_loss: 0.8768 - learning_rate: 3.0000e-04
Epoch 14/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 0s 212ms/step - amount_output_loss: 0.8365 - event_output_loss: 0.5449 - event_output_pr_auc: 0.8347 - loss: 0.9631
Epoch 14: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.
407/407 ━━━━━━━━━━━━━━━━━━━━ 96s 235ms/step - amount_output_loss: 0.8467 - event_output_loss: 0.5432 - event_output_pr_auc: 0.8343 - loss: 0.9691 - val_amount_output_loss: 0.7008 - val_event_output_loss: 0.5162 - val_event_output_pr_auc: 0.8272 - val_loss: 0.8757 - learning_rate: 3.0000e-04
Epoch 15/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 96s 235ms/step - amount_output_loss: 0.8334 - event_output_loss: 0.5416 - event_output_pr_auc: 0.8358 - loss: 0.9604 - val_amount_output_loss: 0.7019 - val_event_output_loss: 0.5154 - val_event_output_pr_auc: 0.8278 - val_loss: 0.8752 - learning_rate: 1.5000e-04
Epoch 15: early stopping
Restoring model weights from the end of the best epoch: 12.
Validation RMSE: 168286.709750
Validation MAE: 28372.294159
Validation R²: 0.067871

Trial 4 of 15
{'tweedie_power': 1.9, 'spatial_dropout': 0.0, 'lstm_units_2': 32, 'lstm_units_1': 32, 'lstm_dropout': 0.2, 'learning_rate': 0.0001, 'dense_units_2': 16, 'dense_units_1': 32, 'dense_dropout': 0.25, 'clipnorm': 2.0, 'batch_size': 512, 'amount_loss_weight': 5.0}
Epoch 1/15
    407/Unknown 55s 121ms/step - amount_output_loss: 9.8721 - event_output_loss: 0.7687 - event_output_pr_auc: 0.6296 - loss: 50.1291

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\trainers\epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

407/407 ━━━━━━━━━━━━━━━━━━━━ 62s 137ms/step - amount_output_loss: 9.0331 - event_output_loss: 0.7625 - event_output_pr_auc: 0.6798 - loss: 46.0439 - val_amount_output_loss: 8.3934 - val_event_output_loss: 0.6648 - val_event_output_pr_auc: 0.7695 - val_loss: 43.1030 - learning_rate: 1.0000e-04
Epoch 2/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 60s 146ms/step - amount_output_loss: 8.0859 - event_output_loss: 0.6829 - event_output_pr_auc: 0.7349 - loss: 41.2141 - val_amount_output_loss: 8.2412 - val_event_output_loss: 0.6140 - val_event_output_pr_auc: 0.7687 - val_loss: 42.2857 - learning_rate: 1.0000e-04
Epoch 3/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 56s 136ms/step - amount_output_loss: 7.9494 - event_output_loss: 0.6506 - event_output_pr_auc: 0.7245 - loss: 40.4978 - val_amount_output_loss: 8.1967 - val_event_output_loss: 0.6018 - val_event_output_pr_auc: 0.7653 - val_loss: 42.0511 - learning_rate: 1.0000e-04
Epoch 4/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 67s 165ms/step - amount_output_loss: 7.9087 - event_output_loss: 0.6432 - event_output_pr_auc: 0.7232 - loss: 40.2839 - val_amount_output_loss: 8.1605 - val_event_output_loss: 0.5969 - val_event_output_pr_auc: 0.7751 - val_loss: 41.8659 - learning_rate: 1.0000e-04
Epoch 5/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 72s 178ms/step - amount_output_loss: 7.8203 - event_output_loss: 0.6396 - event_output_pr_auc: 0.7245 - loss: 39.8380 - val_amount_output_loss: 8.1224 - val_event_output_loss: 0.5878 - val_event_output_pr_auc: 0.7876 - val_loss: 41.6547 - learning_rate: 1.0000e-04
Epoch 6/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 62s 151ms/step - amount_output_loss: 7.7934 - event_output_loss: 0.6331 - event_output_pr_auc: 0.7337 - loss: 39.6995 - val_amount_output_loss: 8.0971 - val_event_output_loss: 0.5830 - val_event_output_pr_auc: 0.7957 - val_loss: 41.5234 - learning_rate: 1.0000e-04
Epoch 7/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 60s 147ms/step - amount_output_loss: 7.7474 - event_output_loss: 0.6273 - event_output_pr_auc: 0.7423 - loss: 39.4631 - val_amount_output_loss: 8.1684 - val_event_output_loss: 0.5781 - val_event_output_pr_auc: 0.7984 - val_loss: 41.8742 - learning_rate: 1.0000e-04
Epoch 8/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - amount_output_loss: 7.7526 - event_output_loss: 0.6251 - event_output_pr_auc: 0.7469 - loss: 39.3882
Epoch 8: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
407/407 ━━━━━━━━━━━━━━━━━━━━ 67s 165ms/step - amount_output_loss: 7.7271 - event_output_loss: 0.6221 - event_output_pr_auc: 0.7487 - loss: 39.3580 - val_amount_output_loss: 8.1124 - val_event_output_loss: 0.5724 - val_event_output_pr_auc: 0.8044 - val_loss: 41.5877 - learning_rate: 1.0000e-04
Epoch 9/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 57s 140ms/step - amount_output_loss: 7.7024 - event_output_loss: 0.6179 - event_output_pr_auc: 0.7557 - loss: 39.2273 - val_amount_output_loss: 8.1487 - val_event_output_loss: 0.5697 - val_event_output_pr_auc: 0.8051 - val_loss: 41.7626 - learning_rate: 5.0000e-05
Epoch 9: early stopping
Restoring model weights from the end of the best epoch: 6.
Validation RMSE: 168571.384868
Validation MAE: 27258.943729
Validation R²: 0.064715

Trial 5 of 15
{'tweedie_power': 1.7, 'spatial_dropout': 0.1, 'lstm_units_2': 32, 'lstm_units_1': 128, 'lstm_dropout': 0.3, 'learning_rate': 0.003, 'dense_units_2': 16, 'dense_units_1': 128, 'dense_dropout': 0.4, 'clipnorm': 2.0, 'batch_size': 512, 'amount_loss_weight': 0.5}
Epoch 1/15
    407/Unknown 179s 428ms/step - amount_output_loss: 2.1621 - event_output_loss: 0.5954 - event_output_pr_auc: 0.7784 - loss: 1.6765

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\trainers\epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

407/407 ━━━━━━━━━━━━━━━━━━━━ 192s 458ms/step - amount_output_loss: 2.0466 - event_output_loss: 0.5786 - event_output_pr_auc: 0.7957 - loss: 1.6058 - val_amount_output_loss: 1.6728 - val_event_output_loss: 0.5215 - val_event_output_pr_auc: 0.8229 - val_loss: 1.3724 - learning_rate: 0.0030
Epoch 2/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 164s 403ms/step - amount_output_loss: 1.9162 - event_output_loss: 0.5626 - event_output_pr_auc: 0.8128 - loss: 1.5246 - val_amount_output_loss: 1.6765 - val_event_output_loss: 0.5177 - val_event_output_pr_auc: 0.8249 - val_loss: 1.3695 - learning_rate: 0.0030
Epoch 3/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 192s 471ms/step - amount_output_loss: 1.8805 - event_output_loss: 0.5559 - event_output_pr_auc: 0.8198 - loss: 1.4997 - val_amount_output_loss: 1.6970 - val_event_output_loss: 0.5155 - val_event_output_pr_auc: 0.8270 - val_loss: 1.3781 - learning_rate: 0.0030
Epoch 4/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 0s 345ms/step - amount_output_loss: 1.8432 - event_output_loss: 0.5528 - event_output_pr_auc: 0.8245 - loss: 1.4744
Epoch 4: ReduceLROnPlateau reducing learning rate to 0.001500000013038516.
407/407 ━━━━━━━━━━━━━━━━━━━━ 153s 376ms/step - amount_output_loss: 1.8454 - event_output_loss: 0.5519 - event_output_pr_auc: 0.8249 - loss: 1.4784 - val_amount_output_loss: 1.6843 - val_event_output_loss: 0.5193 - val_event_output_pr_auc: 0.8209 - val_loss: 1.3745 - learning_rate: 0.0030
Epoch 5/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 181s 445ms/step - amount_output_loss: 1.8134 - event_output_loss: 0.5463 - event_output_pr_auc: 0.8303 - loss: 1.4567 - val_amount_output_loss: 1.6700 - val_event_output_loss: 0.5152 - val_event_output_pr_auc: 0.8238 - val_loss: 1.3638 - learning_rate: 0.0015
Epoch 6/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 201s 493ms/step - amount_output_loss: 1.7710 - event_output_loss: 0.5422 - event_output_pr_auc: 0.8345 - loss: 1.4314 - val_amount_output_loss: 1.6317 - val_event_output_loss: 0.5081 - val_event_output_pr_auc: 0.8302 - val_loss: 1.3373 - learning_rate: 0.0015
Epoch 7/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 195s 479ms/step - amount_output_loss: 1.7375 - event_output_loss: 0.5395 - event_output_pr_auc: 0.8372 - loss: 1.4117 - val_amount_output_loss: 1.6203 - val_event_output_loss: 0.5079 - val_event_output_pr_auc: 0.8324 - val_loss: 1.3303 - learning_rate: 0.0015
Epoch 8/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 194s 477ms/step - amount_output_loss: 1.7341 - event_output_loss: 0.5383 - event_output_pr_auc: 0.8379 - loss: 1.4089 - val_amount_output_loss: 1.6381 - val_event_output_loss: 0.5149 - val_event_output_pr_auc: 0.8244 - val_loss: 1.3471 - learning_rate: 0.0015
Epoch 9/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 0s 458ms/step - amount_output_loss: 1.7316 - event_output_loss: 0.5380 - event_output_pr_auc: 0.8402 - loss: 1.4038
Epoch 9: ReduceLROnPlateau reducing learning rate to 0.000750000006519258.
407/407 ━━━━━━━━━━━━━━━━━━━━ 204s 500ms/step - amount_output_loss: 1.7187 - event_output_loss: 0.5366 - event_output_pr_auc: 0.8398 - loss: 1.3995 - val_amount_output_loss: 1.6430 - val_event_output_loss: 0.5093 - val_event_output_pr_auc: 0.8295 - val_loss: 1.3437 - learning_rate: 0.0015
Epoch 10/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 190s 468ms/step - amount_output_loss: 1.6892 - event_output_loss: 0.5332 - event_output_pr_auc: 0.8425 - loss: 1.3813 - val_amount_output_loss: 1.6097 - val_event_output_loss: 0.5055 - val_event_output_pr_auc: 0.8333 - val_loss: 1.3229 - learning_rate: 7.5000e-04
Epoch 11/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 194s 477ms/step - amount_output_loss: 1.6710 - event_output_loss: 0.5312 - event_output_pr_auc: 0.8441 - loss: 1.3700 - val_amount_output_loss: 1.6412 - val_event_output_loss: 0.5098 - val_event_output_pr_auc: 0.8286 - val_loss: 1.3434 - learning_rate: 7.5000e-04
Epoch 12/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 0s 438ms/step - amount_output_loss: 1.6760 - event_output_loss: 0.5325 - event_output_pr_auc: 0.8444 - loss: 1.3705
Epoch 12: ReduceLROnPlateau reducing learning rate to 0.000375000003259629.
407/407 ━━━━━━━━━━━━━━━━━━━━ 197s 485ms/step - amount_output_loss: 1.6704 - event_output_loss: 0.5317 - event_output_pr_auc: 0.8441 - loss: 1.3703 - val_amount_output_loss: 1.6331 - val_event_output_loss: 0.5098 - val_event_output_pr_auc: 0.8290 - val_loss: 1.3395 - learning_rate: 7.5000e-04
Epoch 13/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 191s 470ms/step - amount_output_loss: 1.6380 - event_output_loss: 0.5280 - event_output_pr_auc: 0.8470 - loss: 1.3503 - val_amount_output_loss: 1.6318 - val_event_output_loss: 0.5090 - val_event_output_pr_auc: 0.8300 - val_loss: 1.3379 - learning_rate: 3.7500e-04
Epoch 13: early stopping
Restoring model weights from the end of the best epoch: 10.
Validation RMSE: 167925.671652
Validation MAE: 30103.654927
Validation R²: 0.071866

Trial 6 of 15
{'tweedie_power': 1.7, 'spatial_dropout': 0.0, 'lstm_units_2': 32, 'lstm_units_1': 128, 'lstm_dropout': 0.1, 'learning_rate': 0.0001, 'dense_units_2': 64, 'dense_units_1': 64, 'dense_dropout': 0.25, 'clipnorm': 2.0, 'batch_size': 256, 'amount_loss_weight': 0.5}
Epoch 1/15
    814/Unknown 161s 191ms/step - amount_output_loss: 2.6162 - event_output_loss: 0.6585 - event_output_pr_auc: 0.7187 - loss: 1.9666

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\trainers\epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

814/814 ━━━━━━━━━━━━━━━━━━━━ 178s 212ms/step - amount_output_loss: 2.2042 - event_output_loss: 0.6065 - event_output_pr_auc: 0.7706 - loss: 1.7112 - val_amount_output_loss: 1.7662 - val_event_output_loss: 0.5304 - val_event_output_pr_auc: 0.8154 - val_loss: 1.4215 - learning_rate: 1.0000e-04
Epoch 2/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 171s 210ms/step - amount_output_loss: 1.9240 - event_output_loss: 0.5642 - event_output_pr_auc: 0.8111 - loss: 1.5286 - val_amount_output_loss: 1.7144 - val_event_output_loss: 0.5212 - val_event_output_pr_auc: 0.8234 - val_loss: 1.3857 - learning_rate: 1.0000e-04
Epoch 3/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 169s 207ms/step - amount_output_loss: 1.8910 - event_output_loss: 0.5586 - event_output_pr_auc: 0.8184 - loss: 1.5061 - val_amount_output_loss: 1.7231 - val_event_output_loss: 0.5238 - val_event_output_pr_auc: 0.8205 - val_loss: 1.3926 - learning_rate: 1.0000e-04
Epoch 4/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 174s 213ms/step - amount_output_loss: 1.8513 - event_output_loss: 0.5548 - event_output_pr_auc: 0.8227 - loss: 1.4819 - val_amount_output_loss: 1.7065 - val_event_output_loss: 0.5232 - val_event_output_pr_auc: 0.8203 - val_loss: 1.3835 - learning_rate: 1.0000e-04
Epoch 5/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 176s 216ms/step - amount_output_loss: 1.8341 - event_output_loss: 0.5517 - event_output_pr_auc: 0.8261 - loss: 1.4708 - val_amount_output_loss: 1.6844 - val_event_output_loss: 0.5208 - val_event_output_pr_auc: 0.8234 - val_loss: 1.3700 - learning_rate: 1.0000e-04
Epoch 6/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 182s 224ms/step - amount_output_loss: 1.8126 - event_output_loss: 0.5484 - event_output_pr_auc: 0.8294 - loss: 1.4565 - val_amount_output_loss: 1.7016 - val_event_output_loss: 0.5215 - val_event_output_pr_auc: 0.8217 - val_loss: 1.3795 - learning_rate: 1.0000e-04
Epoch 7/15
813/814 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step - amount_output_loss: 1.8011 - event_output_loss: 0.5461 - event_output_pr_auc: 0.8315 - loss: 1.4467
Epoch 7: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
814/814 ━━━━━━━━━━━━━━━━━━━━ 181s 222ms/step - amount_output_loss: 1.7949 - event_output_loss: 0.5459 - event_output_pr_auc: 0.8322 - loss: 1.4449 - val_amount_output_loss: 1.7099 - val_event_output_loss: 0.5233 - val_event_output_pr_auc: 0.8206 - val_loss: 1.3856 - learning_rate: 1.0000e-04
Epoch 8/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 180s 221ms/step - amount_output_loss: 1.7648 - event_output_loss: 0.5430 - event_output_pr_auc: 0.8348 - loss: 1.4278 - val_amount_output_loss: 1.6796 - val_event_output_loss: 0.5207 - val_event_output_pr_auc: 0.8217 - val_loss: 1.3674 - learning_rate: 5.0000e-05
Epoch 9/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 181s 223ms/step - amount_output_loss: 1.7504 - event_output_loss: 0.5417 - event_output_pr_auc: 0.8360 - loss: 1.4189 - val_amount_output_loss: 1.6865 - val_event_output_loss: 0.5194 - val_event_output_pr_auc: 0.8234 - val_loss: 1.3697 - learning_rate: 5.0000e-05
Epoch 10/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 184s 226ms/step - amount_output_loss: 1.7464 - event_output_loss: 0.5405 - event_output_pr_auc: 0.8374 - loss: 1.4146 - val_amount_output_loss: 1.6733 - val_event_output_loss: 0.5188 - val_event_output_pr_auc: 0.8241 - val_loss: 1.3623 - learning_rate: 5.0000e-05
Epoch 11/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 181s 222ms/step - amount_output_loss: 1.7366 - event_output_loss: 0.5394 - event_output_pr_auc: 0.8384 - loss: 1.4097 - val_amount_output_loss: 1.6681 - val_event_output_loss: 0.5166 - val_event_output_pr_auc: 0.8253 - val_loss: 1.3574 - learning_rate: 5.0000e-05
Epoch 12/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 183s 224ms/step - amount_output_loss: 1.7274 - event_output_loss: 0.5381 - event_output_pr_auc: 0.8395 - loss: 1.4033 - val_amount_output_loss: 1.6737 - val_event_output_loss: 0.5171 - val_event_output_pr_auc: 0.8251 - val_loss: 1.3607 - learning_rate: 5.0000e-05
Epoch 13/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 0s 204ms/step - amount_output_loss: 1.7342 - event_output_loss: 0.5377 - event_output_pr_auc: 0.8410 - loss: 1.4048
Epoch 13: ReduceLROnPlateau reducing learning rate to 2.499999936844688e-05.
814/814 ━━━━━━━━━━━━━━━━━━━━ 182s 223ms/step - amount_output_loss: 1.7204 - event_output_loss: 0.5369 - event_output_pr_auc: 0.8407 - loss: 1.3990 - val_amount_output_loss: 1.6788 - val_event_output_loss: 0.5163 - val_event_output_pr_auc: 0.8248 - val_loss: 1.3626 - learning_rate: 5.0000e-05
Epoch 14/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 181s 223ms/step - amount_output_loss: 1.7173 - event_output_loss: 0.5354 - event_output_pr_auc: 0.8419 - loss: 1.3957 - val_amount_output_loss: 1.6757 - val_event_output_loss: 0.5174 - val_event_output_pr_auc: 0.8245 - val_loss: 1.3620 - learning_rate: 2.5000e-05
Epoch 14: early stopping
Restoring model weights from the end of the best epoch: 11.
Validation RMSE: 167903.609688
Validation MAE: 28115.471152
Validation R²: 0.072110

Trial 7 of 15
{'tweedie_power': 1.1, 'spatial_dropout': 0.0, 'lstm_units_2': 64, 'lstm_units_1': 64, 'lstm_dropout': 0.3, 'learning_rate': 0.003, 'dense_units_2': 32, 'dense_units_1': 32, 'dense_dropout': 0.4, 'clipnorm': 1.0, 'batch_size': 1024, 'amount_loss_weight': 1.0}
Epoch 1/15
    204/Unknown 89s 409ms/step - amount_output_loss: 0.6426 - event_output_loss: 0.6177 - event_output_pr_auc: 0.7559 - loss: 1.2602

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\trainers\epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

204/204 ━━━━━━━━━━━━━━━━━━━━ 97s 449ms/step - amount_output_loss: 0.5169 - event_output_loss: 0.5850 - event_output_pr_auc: 0.7882 - loss: 1.1083 - val_amount_output_loss: 0.2873 - val_event_output_loss: 0.5187 - val_event_output_pr_auc: 0.8239 - val_loss: 0.8244 - learning_rate: 0.0030
Epoch 2/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 88s 432ms/step - amount_output_loss: 0.4482 - event_output_loss: 0.5599 - event_output_pr_auc: 0.8149 - loss: 1.0133 - val_amount_output_loss: 0.3044 - val_event_output_loss: 0.5377 - val_event_output_pr_auc: 0.8199 - val_loss: 0.8612 - learning_rate: 0.0030
Epoch 3/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 0s 434ms/step - amount_output_loss: 0.4352 - event_output_loss: 0.5571 - event_output_pr_auc: 0.8211 - loss: 0.9923
Epoch 3: ReduceLROnPlateau reducing learning rate to 0.001500000013038516.
204/204 ━━━━━━━━━━━━━━━━━━━━ 96s 472ms/step - amount_output_loss: 0.4230 - event_output_loss: 0.5529 - event_output_pr_auc: 0.8220 - loss: 0.9812 - val_amount_output_loss: 0.3210 - val_event_output_loss: 0.5245 - val_event_output_pr_auc: 0.8206 - val_loss: 0.8645 - learning_rate: 0.0030
Epoch 4/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 88s 431ms/step - amount_output_loss: 0.4011 - event_output_loss: 0.5453 - event_output_pr_auc: 0.8284 - loss: 0.9513 - val_amount_output_loss: 0.3011 - val_event_output_loss: 0.5219 - val_event_output_pr_auc: 0.8284 - val_loss: 0.8418 - learning_rate: 0.0015
Epoch 4: early stopping
Restoring model weights from the end of the best epoch: 1.
Validation RMSE: 167076.605735
Validation MAE: 29223.587747
Validation R²: 0.081228
New best LSTM model found.

Trial 8 of 15
{'tweedie_power': 1.5, 'spatial_dropout': 0.0, 'lstm_units_2': 32, 'lstm_units_1': 128, 'lstm_dropout': 0.2, 'learning_rate': 0.0001, 'dense_units_2': 16, 'dense_units_1': 128, 'dense_dropout': 0.1, 'clipnorm': 1.0, 'batch_size': 1024, 'amount_loss_weight': 2.0}
Epoch 1/15
    204/Unknown 131s 612ms/step - amount_output_loss: 1.8107 - event_output_loss: 0.6804 - event_output_pr_auc: 0.6621 - loss: 4.3019

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\trainers\epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

204/204 ━━━━━━━━━━━━━━━━━━━━ 143s 672ms/step - amount_output_loss: 1.3010 - event_output_loss: 0.6480 - event_output_pr_auc: 0.7280 - loss: 3.2699 - val_amount_output_loss: 0.7528 - val_event_output_loss: 0.5657 - val_event_output_pr_auc: 0.7924 - val_loss: 2.1207 - learning_rate: 1.0000e-04
Epoch 2/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 140s 687ms/step - amount_output_loss: 0.9207 - event_output_loss: 0.5877 - event_output_pr_auc: 0.7818 - loss: 2.4414 - val_amount_output_loss: 0.7181 - val_event_output_loss: 0.5353 - val_event_output_pr_auc: 0.8049 - val_loss: 2.0179 - learning_rate: 1.0000e-04
Epoch 3/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 141s 691ms/step - amount_output_loss: 0.8950 - event_output_loss: 0.5725 - event_output_pr_auc: 0.7930 - loss: 2.3707 - val_amount_output_loss: 0.7220 - val_event_output_loss: 0.5261 - val_event_output_pr_auc: 0.8145 - val_loss: 2.0166 - learning_rate: 1.0000e-04
Epoch 4/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 142s 695ms/step - amount_output_loss: 0.8763 - event_output_loss: 0.5654 - event_output_pr_auc: 0.8020 - loss: 2.3308 - val_amount_output_loss: 0.7140 - val_event_output_loss: 0.5177 - val_event_output_pr_auc: 0.8201 - val_loss: 1.9916 - learning_rate: 1.0000e-04
Epoch 5/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 144s 707ms/step - amount_output_loss: 0.8636 - event_output_loss: 0.5607 - event_output_pr_auc: 0.8087 - loss: 2.2997 - val_amount_output_loss: 0.7013 - val_event_output_loss: 0.5154 - val_event_output_pr_auc: 0.8222 - val_loss: 1.9629 - learning_rate: 1.0000e-04
Epoch 6/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 139s 683ms/step - amount_output_loss: 0.8516 - event_output_loss: 0.5579 - event_output_pr_auc: 0.8123 - loss: 2.2725 - val_amount_output_loss: 0.7026 - val_event_output_loss: 0.5142 - val_event_output_pr_auc: 0.8246 - val_loss: 1.9643 - learning_rate: 1.0000e-04
Epoch 7/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 0s 655ms/step - amount_output_loss: 0.8491 - event_output_loss: 0.5573 - event_output_pr_auc: 0.8179 - loss: 2.2555
Epoch 7: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
204/204 ━━━━━━━━━━━━━━━━━━━━ 144s 707ms/step - amount_output_loss: 0.8390 - event_output_loss: 0.5556 - event_output_pr_auc: 0.8155 - loss: 2.2456 - val_amount_output_loss: 0.7067 - val_event_output_loss: 0.5123 - val_event_output_pr_auc: 0.8260 - val_loss: 1.9708 - learning_rate: 1.0000e-04
Epoch 8/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 142s 695ms/step - amount_output_loss: 0.8298 - event_output_loss: 0.5541 - event_output_pr_auc: 0.8175 - loss: 2.2251 - val_amount_output_loss: 0.7046 - val_event_output_loss: 0.5117 - val_event_output_pr_auc: 0.8263 - val_loss: 1.9660 - learning_rate: 5.0000e-05
Epoch 8: early stopping
Restoring model weights from the end of the best epoch: 5.
Validation RMSE: 167167.389343
Validation MAE: 27720.136148
Validation R²: 0.080229

Trial 9 of 15
{'tweedie_power': 1.5, 'spatial_dropout': 0.2, 'lstm_units_2': 64, 'lstm_units_1': 32, 'lstm_dropout': 0.1, 'learning_rate': 0.003, 'dense_units_2': 16, 'dense_units_1': 64, 'dense_dropout': 0.1, 'clipnorm': 0.5, 'batch_size': 512, 'amount_loss_weight': 0.5}
Epoch 1/15
    407/Unknown 80s 182ms/step - amount_output_loss: 1.1103 - event_output_loss: 0.5935 - event_output_pr_auc: 0.7794 - loss: 1.1486

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\trainers\epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

407/407 ━━━━━━━━━━━━━━━━━━━━ 89s 204ms/step - amount_output_loss: 0.9915 - event_output_loss: 0.5754 - event_output_pr_auc: 0.7983 - loss: 1.0739 - val_amount_output_loss: 0.7112 - val_event_output_loss: 0.5255 - val_event_output_pr_auc: 0.8206 - val_loss: 0.8906 - learning_rate: 0.0030
Epoch 2/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 86s 210ms/step - amount_output_loss: 0.9214 - event_output_loss: 0.5604 - event_output_pr_auc: 0.8146 - loss: 1.0236 - val_amount_output_loss: 0.7066 - val_event_output_loss: 0.5131 - val_event_output_pr_auc: 0.8275 - val_loss: 0.8757 - learning_rate: 0.0030
Epoch 3/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 80s 196ms/step - amount_output_loss: 0.8993 - event_output_loss: 0.5550 - event_output_pr_auc: 0.8216 - loss: 1.0072 - val_amount_output_loss: 0.6928 - val_event_output_loss: 0.5217 - val_event_output_pr_auc: 0.8259 - val_loss: 0.8771 - learning_rate: 0.0030
Epoch 4/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 87s 213ms/step - amount_output_loss: 0.8690 - event_output_loss: 0.5508 - event_output_pr_auc: 0.8259 - loss: 0.9878 - val_amount_output_loss: 0.6982 - val_event_output_loss: 0.5086 - val_event_output_pr_auc: 0.8300 - val_loss: 0.8660 - learning_rate: 0.0030
Epoch 5/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 80s 197ms/step - amount_output_loss: 0.8642 - event_output_loss: 0.5489 - event_output_pr_auc: 0.8272 - loss: 0.9836 - val_amount_output_loss: 0.6751 - val_event_output_loss: 0.5154 - val_event_output_pr_auc: 0.8255 - val_loss: 0.8617 - learning_rate: 0.0030
Epoch 6/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 88s 216ms/step - amount_output_loss: 0.8555 - event_output_loss: 0.5458 - event_output_pr_auc: 0.8306 - loss: 0.9760 - val_amount_output_loss: 0.6825 - val_event_output_loss: 0.5122 - val_event_output_pr_auc: 0.8310 - val_loss: 0.8623 - learning_rate: 0.0030
Epoch 7/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - amount_output_loss: 0.8332 - event_output_loss: 0.5444 - event_output_pr_auc: 0.8332 - loss: 0.9610
Epoch 7: ReduceLROnPlateau reducing learning rate to 0.001500000013038516.
407/407 ━━━━━━━━━━━━━━━━━━━━ 80s 196ms/step - amount_output_loss: 0.8420 - event_output_loss: 0.5439 - event_output_pr_auc: 0.8327 - loss: 0.9673 - val_amount_output_loss: 0.6923 - val_event_output_loss: 0.5096 - val_event_output_pr_auc: 0.8328 - val_loss: 0.8645 - learning_rate: 0.0030
Epoch 8/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 88s 216ms/step - amount_output_loss: 0.8267 - event_output_loss: 0.5411 - event_output_pr_auc: 0.8349 - loss: 0.9568 - val_amount_output_loss: 0.6747 - val_event_output_loss: 0.5103 - val_event_output_pr_auc: 0.8295 - val_loss: 0.8562 - learning_rate: 0.0015
Epoch 9/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 82s 202ms/step - amount_output_loss: 0.8220 - event_output_loss: 0.5397 - event_output_pr_auc: 0.8365 - loss: 0.9531 - val_amount_output_loss: 0.6950 - val_event_output_loss: 0.5139 - val_event_output_pr_auc: 0.8255 - val_loss: 0.8701 - learning_rate: 0.0015
Epoch 10/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 0s 190ms/step - amount_output_loss: 0.8149 - event_output_loss: 0.5383 - event_output_pr_auc: 0.8392 - loss: 0.9458
Epoch 10: ReduceLROnPlateau reducing learning rate to 0.000750000006519258.
407/407 ━━━━━━━━━━━━━━━━━━━━ 85s 209ms/step - amount_output_loss: 0.8134 - event_output_loss: 0.5376 - event_output_pr_auc: 0.8386 - loss: 0.9466 - val_amount_output_loss: 0.6847 - val_event_output_loss: 0.5157 - val_event_output_pr_auc: 0.8268 - val_loss: 0.8670 - learning_rate: 0.0015
Epoch 11/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 83s 203ms/step - amount_output_loss: 0.8023 - event_output_loss: 0.5357 - event_output_pr_auc: 0.8399 - loss: 0.9393 - val_amount_output_loss: 0.6779 - val_event_output_loss: 0.5105 - val_event_output_pr_auc: 0.8297 - val_loss: 0.8582 - learning_rate: 7.5000e-04
Epoch 11: early stopping
Restoring model weights from the end of the best epoch: 8.
Validation RMSE: 166661.342756
Validation MAE: 28067.721400
Validation R²: 0.085790
New best LSTM model found.

Trial 10 of 15
{'tweedie_power': 1.1, 'spatial_dropout': 0.1, 'lstm_units_2': 64, 'lstm_units_1': 64, 'lstm_dropout': 0.3, 'learning_rate': 0.0001, 'dense_units_2': 64, 'dense_units_1': 64, 'dense_dropout': 0.4, 'clipnorm': 1.0, 'batch_size': 512, 'amount_loss_weight': 2.0}
Epoch 1/15
    407/Unknown 110s 260ms/step - amount_output_loss: 0.8703 - event_output_loss: 0.6863 - event_output_pr_auc: 0.6378 - loss: 2.4270

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\trainers\epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

407/407 ━━━━━━━━━━━━━━━━━━━━ 121s 288ms/step - amount_output_loss: 0.6619 - event_output_loss: 0.6536 - event_output_pr_auc: 0.6998 - loss: 1.9829 - val_amount_output_loss: 0.3071 - val_event_output_loss: 0.5588 - val_event_output_pr_auc: 0.7850 - val_loss: 1.1895 - learning_rate: 1.0000e-04
Epoch 2/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 112s 274ms/step - amount_output_loss: 0.5124 - event_output_loss: 0.5985 - event_output_pr_auc: 0.7722 - loss: 1.6280 - val_amount_output_loss: 0.3051 - val_event_output_loss: 0.5428 - val_event_output_pr_auc: 0.8043 - val_loss: 1.1689 - learning_rate: 1.0000e-04
Epoch 3/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 116s 286ms/step - amount_output_loss: 0.4969 - event_output_loss: 0.5840 - event_output_pr_auc: 0.7895 - loss: 1.5820 - val_amount_output_loss: 0.2931 - val_event_output_loss: 0.5328 - val_event_output_pr_auc: 0.8144 - val_loss: 1.1341 - learning_rate: 1.0000e-04
Epoch 4/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 117s 287ms/step - amount_output_loss: 0.4798 - event_output_loss: 0.5781 - event_output_pr_auc: 0.7953 - loss: 1.5417 - val_amount_output_loss: 0.2920 - val_event_output_loss: 0.5308 - val_event_output_pr_auc: 0.8176 - val_loss: 1.1301 - learning_rate: 1.0000e-04
Epoch 5/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 110s 271ms/step - amount_output_loss: 0.4628 - event_output_loss: 0.5735 - event_output_pr_auc: 0.8006 - loss: 1.5033 - val_amount_output_loss: 0.2885 - val_event_output_loss: 0.5277 - val_event_output_pr_auc: 0.8205 - val_loss: 1.1198 - learning_rate: 1.0000e-04
Epoch 6/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 116s 284ms/step - amount_output_loss: 0.4520 - event_output_loss: 0.5715 - event_output_pr_auc: 0.8028 - loss: 1.4793 - val_amount_output_loss: 0.2895 - val_event_output_loss: 0.5245 - val_event_output_pr_auc: 0.8225 - val_loss: 1.1185 - learning_rate: 1.0000e-04
Epoch 7/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 114s 281ms/step - amount_output_loss: 0.4575 - event_output_loss: 0.5706 - event_output_pr_auc: 0.8046 - loss: 1.4886 - val_amount_output_loss: 0.2901 - val_event_output_loss: 0.5254 - val_event_output_pr_auc: 0.8230 - val_loss: 1.1207 - learning_rate: 1.0000e-04
Epoch 8/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 0s 246ms/step - amount_output_loss: 0.4661 - event_output_loss: 0.5699 - event_output_pr_auc: 0.8059 - loss: 1.5020
Epoch 8: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
407/407 ━━━━━━━━━━━━━━━━━━━━ 110s 269ms/step - amount_output_loss: 0.4460 - event_output_loss: 0.5690 - event_output_pr_auc: 0.8061 - loss: 1.4650 - val_amount_output_loss: 0.2909 - val_event_output_loss: 0.5246 - val_event_output_pr_auc: 0.8242 - val_loss: 1.1215 - learning_rate: 1.0000e-04
Epoch 9/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 117s 287ms/step - amount_output_loss: 0.4376 - event_output_loss: 0.5675 - event_output_pr_auc: 0.8088 - loss: 1.4462 - val_amount_output_loss: 0.2878 - val_event_output_loss: 0.5228 - val_event_output_pr_auc: 0.8251 - val_loss: 1.1131 - learning_rate: 5.0000e-05
Epoch 10/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 111s 272ms/step - amount_output_loss: 0.4346 - event_output_loss: 0.5665 - event_output_pr_auc: 0.8095 - loss: 1.4388 - val_amount_output_loss: 0.2877 - val_event_output_loss: 0.5231 - val_event_output_pr_auc: 0.8252 - val_loss: 1.1133 - learning_rate: 5.0000e-05
Epoch 11/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 0s 257ms/step - amount_output_loss: 0.4247 - event_output_loss: 0.5660 - event_output_pr_auc: 0.8111 - loss: 1.4154
Epoch 11: ReduceLROnPlateau reducing learning rate to 2.499999936844688e-05.
407/407 ━━━━━━━━━━━━━━━━━━━━ 114s 280ms/step - amount_output_loss: 0.4361 - event_output_loss: 0.5660 - event_output_pr_auc: 0.8098 - loss: 1.4421 - val_amount_output_loss: 0.2902 - val_event_output_loss: 0.5233 - val_event_output_pr_auc: 0.8249 - val_loss: 1.1185 - learning_rate: 5.0000e-05
Epoch 12/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 117s 288ms/step - amount_output_loss: 0.4308 - event_output_loss: 0.5663 - event_output_pr_auc: 0.8100 - loss: 1.4318 - val_amount_output_loss: 0.2884 - val_event_output_loss: 0.5230 - val_event_output_pr_auc: 0.8250 - val_loss: 1.1145 - learning_rate: 2.5000e-05
Epoch 12: early stopping
Restoring model weights from the end of the best epoch: 9.
Validation RMSE: 166977.637450
Validation MAE: 29864.242018
Validation R²: 0.082316

Trial 11 of 15
{'tweedie_power': 1.3, 'spatial_dropout': 0.0, 'lstm_units_2': 16, 'lstm_units_1': 128, 'lstm_dropout': 0.2, 'learning_rate': 0.0001, 'dense_units_2': 16, 'dense_units_1': 128, 'dense_dropout': 0.4, 'clipnorm': 2.0, 'batch_size': 1024, 'amount_loss_weight': 5.0}
Epoch 1/15
    204/Unknown 118s 553ms/step - amount_output_loss: 1.1468 - event_output_loss: 0.7398 - event_output_pr_auc: 0.5387 - loss: 6.4741

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\trainers\epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

204/204 ━━━━━━━━━━━━━━━━━━━━ 129s 610ms/step - amount_output_loss: 0.8623 - event_output_loss: 0.7246 - event_output_pr_auc: 0.5477 - loss: 5.0661 - val_amount_output_loss: 0.4573 - val_event_output_loss: 0.6267 - val_event_output_pr_auc: 0.7328 - val_loss: 2.9888 - learning_rate: 1.0000e-04
Epoch 2/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 126s 619ms/step - amount_output_loss: 0.6354 - event_output_loss: 0.6402 - event_output_pr_auc: 0.7145 - loss: 3.8374 - val_amount_output_loss: 0.4421 - val_event_output_loss: 0.5733 - val_event_output_pr_auc: 0.7846 - val_loss: 2.8556 - learning_rate: 1.0000e-04
Epoch 3/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 129s 633ms/step - amount_output_loss: 0.6044 - event_output_loss: 0.6103 - event_output_pr_auc: 0.7616 - loss: 3.6471 - val_amount_output_loss: 0.4232 - val_event_output_loss: 0.5489 - val_event_output_pr_auc: 0.7966 - val_loss: 2.7325 - learning_rate: 1.0000e-04
Epoch 4/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 125s 615ms/step - amount_output_loss: 0.5864 - event_output_loss: 0.5959 - event_output_pr_auc: 0.7777 - loss: 3.5479 - val_amount_output_loss: 0.4126 - val_event_output_loss: 0.5379 - val_event_output_pr_auc: 0.8019 - val_loss: 2.6669 - learning_rate: 1.0000e-04
Epoch 5/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 127s 623ms/step - amount_output_loss: 0.5776 - event_output_loss: 0.5867 - event_output_pr_auc: 0.7885 - loss: 3.4956 - val_amount_output_loss: 0.4066 - val_event_output_loss: 0.5300 - val_event_output_pr_auc: 0.8132 - val_loss: 2.6279 - learning_rate: 1.0000e-04
Epoch 6/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 132s 648ms/step - amount_output_loss: 0.5650 - event_output_loss: 0.5801 - event_output_pr_auc: 0.7960 - loss: 3.4257 - val_amount_output_loss: 0.4085 - val_event_output_loss: 0.5248 - val_event_output_pr_auc: 0.8184 - val_loss: 2.6322 - learning_rate: 1.0000e-04
Epoch 7/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 0s 580ms/step - amount_output_loss: 0.5474 - event_output_loss: 0.5794 - event_output_pr_auc: 0.8002 - loss: 3.3163
Epoch 7: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
204/204 ━━━━━━━━━━━━━━━━━━━━ 129s 632ms/step - amount_output_loss: 0.5566 - event_output_loss: 0.5749 - event_output_pr_auc: 0.8015 - loss: 3.3775 - val_amount_output_loss: 0.4095 - val_event_output_loss: 0.5225 - val_event_output_pr_auc: 0.8196 - val_loss: 2.6353 - learning_rate: 1.0000e-04
Epoch 8/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 127s 625ms/step - amount_output_loss: 0.5459 - event_output_loss: 0.5718 - event_output_pr_auc: 0.8047 - loss: 3.3194 - val_amount_output_loss: 0.4099 - val_event_output_loss: 0.5211 - val_event_output_pr_auc: 0.8207 - val_loss: 2.6359 - learning_rate: 5.0000e-05
Epoch 8: early stopping
Restoring model weights from the end of the best epoch: 5.
Validation RMSE: 167330.805207
Validation MAE: 27190.254451
Validation R²: 0.078430

Trial 12 of 15
{'tweedie_power': 1.9, 'spatial_dropout': 0.0, 'lstm_units_2': 16, 'lstm_units_1': 64, 'lstm_dropout': 0.1, 'learning_rate': 0.0003, 'dense_units_2': 64, 'dense_units_1': 128, 'dense_dropout': 0.4, 'clipnorm': 1.0, 'batch_size': 1024, 'amount_loss_weight': 2.0}
Epoch 1/15
    204/Unknown 64s 285ms/step - amount_output_loss: 8.8501 - event_output_loss: 0.6787 - event_output_pr_auc: 0.6527 - loss: 18.3789

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\trainers\epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

204/204 ━━━━━━━━━━━━━━━━━━━━ 70s 314ms/step - amount_output_loss: 8.2306 - event_output_loss: 0.6356 - event_output_pr_auc: 0.7311 - loss: 17.1872 - val_amount_output_loss: 8.0347 - val_event_output_loss: 0.5481 - val_event_output_pr_auc: 0.7941 - val_loss: 17.0066 - learning_rate: 3.0000e-04
Epoch 2/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 60s 295ms/step - amount_output_loss: 7.7678 - event_output_loss: 0.5777 - event_output_pr_auc: 0.7932 - loss: 16.1918 - val_amount_output_loss: 8.0170 - val_event_output_loss: 0.5259 - val_event_output_pr_auc: 0.8132 - val_loss: 16.9459 - learning_rate: 3.0000e-04
Epoch 3/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 62s 305ms/step - amount_output_loss: 7.6898 - event_output_loss: 0.5692 - event_output_pr_auc: 0.8026 - loss: 16.0299 - val_amount_output_loss: 7.9205 - val_event_output_loss: 0.5186 - val_event_output_pr_auc: 0.8195 - val_loss: 16.7409 - learning_rate: 3.0000e-04
Epoch 4/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 63s 309ms/step - amount_output_loss: 7.6196 - event_output_loss: 0.5644 - event_output_pr_auc: 0.8081 - loss: 15.8813 - val_amount_output_loss: 8.0006 - val_event_output_loss: 0.5185 - val_event_output_pr_auc: 0.8225 - val_loss: 16.9054 - learning_rate: 3.0000e-04
Epoch 5/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 0s 273ms/step - amount_output_loss: 7.6053 - event_output_loss: 0.5647 - event_output_pr_auc: 0.8118 - loss: 15.7752
Epoch 5: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.
204/204 ━━━━━━━━━━━━━━━━━━━━ 61s 298ms/step - amount_output_loss: 7.5922 - event_output_loss: 0.5614 - event_output_pr_auc: 0.8119 - loss: 15.8146 - val_amount_output_loss: 7.9537 - val_event_output_loss: 0.5159 - val_event_output_pr_auc: 0.8233 - val_loss: 16.8057 - learning_rate: 3.0000e-04
Epoch 6/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 60s 295ms/step - amount_output_loss: 7.5315 - event_output_loss: 0.5593 - event_output_pr_auc: 0.8135 - loss: 15.7000 - val_amount_output_loss: 7.8815 - val_event_output_loss: 0.5131 - val_event_output_pr_auc: 0.8247 - val_loss: 16.6565 - learning_rate: 1.5000e-04
Epoch 7/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 64s 315ms/step - amount_output_loss: 7.5239 - event_output_loss: 0.5578 - event_output_pr_auc: 0.8153 - loss: 15.6824 - val_amount_output_loss: 7.8948 - val_event_output_loss: 0.5131 - val_event_output_pr_auc: 0.8246 - val_loss: 16.6834 - learning_rate: 1.5000e-04
Epoch 8/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 62s 304ms/step - amount_output_loss: 7.5000 - event_output_loss: 0.5574 - event_output_pr_auc: 0.8160 - loss: 15.6347 - val_amount_output_loss: 7.8693 - val_event_output_loss: 0.5124 - val_event_output_pr_auc: 0.8249 - val_loss: 16.6309 - learning_rate: 1.5000e-04
Epoch 9/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 61s 297ms/step - amount_output_loss: 7.4986 - event_output_loss: 0.5562 - event_output_pr_auc: 0.8171 - loss: 15.6315 - val_amount_output_loss: 7.8742 - val_event_output_loss: 0.5109 - val_event_output_pr_auc: 0.8258 - val_loss: 16.6392 - learning_rate: 1.5000e-04
Epoch 10/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 65s 318ms/step - amount_output_loss: 7.4713 - event_output_loss: 0.5560 - event_output_pr_auc: 0.8173 - loss: 15.5703 - val_amount_output_loss: 7.8651 - val_event_output_loss: 0.5111 - val_event_output_pr_auc: 0.8258 - val_loss: 16.6208 - learning_rate: 1.5000e-04
Epoch 11/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 78s 298ms/step - amount_output_loss: 7.4541 - event_output_loss: 0.5556 - event_output_pr_auc: 0.8179 - loss: 15.5368 - val_amount_output_loss: 7.8701 - val_event_output_loss: 0.5106 - val_event_output_pr_auc: 0.8262 - val_loss: 16.6307 - learning_rate: 1.5000e-04
Epoch 12/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 0s 297ms/step - amount_output_loss: 7.4849 - event_output_loss: 0.5563 - event_output_pr_auc: 0.8192 - loss: 15.5261
Epoch 12: ReduceLROnPlateau reducing learning rate to 7.500000356230885e-05.
204/204 ━━━━━━━━━━━━━━━━━━━━ 66s 325ms/step - amount_output_loss: 7.4438 - event_output_loss: 0.5549 - event_output_pr_auc: 0.8185 - loss: 15.5180 - val_amount_output_loss: 7.8982 - val_event_output_loss: 0.5115 - val_event_output_pr_auc: 0.8259 - val_loss: 16.6892 - learning_rate: 1.5000e-04
Epoch 13/15
204/204 ━━━━━━━━━━━━━━━━━━━━ 66s 323ms/step - amount_output_loss: 7.4284 - event_output_loss: 0.5540 - event_output_pr_auc: 0.8197 - loss: 15.4873 - val_amount_output_loss: 7.8764 - val_event_output_loss: 0.5101 - val_event_output_pr_auc: 0.8266 - val_loss: 16.6432 - learning_rate: 7.5000e-05
Epoch 13: early stopping
Restoring model weights from the end of the best epoch: 10.
Validation RMSE: 167688.903207
Validation MAE: 29526.366194
Validation R²: 0.074482

Trial 13 of 15
{'tweedie_power': 1.3, 'spatial_dropout': 0.1, 'lstm_units_2': 32, 'lstm_units_1': 32, 'lstm_dropout': 0.3, 'learning_rate': 0.0003, 'dense_units_2': 64, 'dense_units_1': 64, 'dense_dropout': 0.4, 'clipnorm': 2.0, 'batch_size': 256, 'amount_loss_weight': 2.0}
Epoch 1/15
    813/Unknown 74s 86ms/step - amount_output_loss: 0.8969 - event_output_loss: 0.6541 - event_output_pr_auc: 0.6931 - loss: 2.4478

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\trainers\epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

814/814 ━━━━━━━━━━━━━━━━━━━━ 81s 95ms/step - amount_output_loss: 0.7288 - event_output_loss: 0.6155 - event_output_pr_auc: 0.7563 - loss: 2.0756 - val_amount_output_loss: 0.4350 - val_event_output_loss: 0.5364 - val_event_output_pr_auc: 0.8155 - val_loss: 1.4155 - learning_rate: 3.0000e-04
Epoch 2/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 77s 95ms/step - amount_output_loss: 0.6144 - event_output_loss: 0.5790 - event_output_pr_auc: 0.7970 - loss: 1.8106 - val_amount_output_loss: 0.4280 - val_event_output_loss: 0.5328 - val_event_output_pr_auc: 0.8228 - val_loss: 1.3980 - learning_rate: 3.0000e-04
Epoch 3/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 73s 89ms/step - amount_output_loss: 0.5913 - event_output_loss: 0.5725 - event_output_pr_auc: 0.8034 - loss: 1.7574 - val_amount_output_loss: 0.4344 - val_event_output_loss: 0.5233 - val_event_output_pr_auc: 0.8265 - val_loss: 1.4012 - learning_rate: 3.0000e-04
Epoch 4/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 79s 97ms/step - amount_output_loss: 0.5763 - event_output_loss: 0.5682 - event_output_pr_auc: 0.8083 - loss: 1.7231 - val_amount_output_loss: 0.4200 - val_event_output_loss: 0.5277 - val_event_output_pr_auc: 0.8258 - val_loss: 1.3766 - learning_rate: 3.0000e-04
Epoch 5/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 74s 91ms/step - amount_output_loss: 0.5670 - event_output_loss: 0.5663 - event_output_pr_auc: 0.8097 - loss: 1.7027 - val_amount_output_loss: 0.4316 - val_event_output_loss: 0.5211 - val_event_output_pr_auc: 0.8281 - val_loss: 1.3931 - learning_rate: 3.0000e-04
Epoch 6/15
813/814 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - amount_output_loss: 0.5775 - event_output_loss: 0.5655 - event_output_pr_auc: 0.8103 - loss: 1.7204
Epoch 6: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.
814/814 ━━━━━━━━━━━━━━━━━━━━ 77s 94ms/step - amount_output_loss: 0.5604 - event_output_loss: 0.5643 - event_output_pr_auc: 0.8117 - loss: 1.6863 - val_amount_output_loss: 0.4237 - val_event_output_loss: 0.5213 - val_event_output_pr_auc: 0.8283 - val_loss: 1.3776 - learning_rate: 3.0000e-04
Epoch 7/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 78s 95ms/step - amount_output_loss: 0.5518 - event_output_loss: 0.5632 - event_output_pr_auc: 0.8124 - loss: 1.6697 - val_amount_output_loss: 0.4429 - val_event_output_loss: 0.5200 - val_event_output_pr_auc: 0.8286 - val_loss: 1.4149 - learning_rate: 1.5000e-04
Epoch 7: early stopping
Restoring model weights from the end of the best epoch: 4.
Validation RMSE: 167610.542002
Validation MAE: 30302.617490
Validation R²: 0.075346

Trial 14 of 15
{'tweedie_power': 1.7, 'spatial_dropout': 0.0, 'lstm_units_2': 32, 'lstm_units_1': 128, 'lstm_dropout': 0.2, 'learning_rate': 0.0001, 'dense_units_2': 16, 'dense_units_1': 32, 'dense_dropout': 0.1, 'clipnorm': 1.0, 'batch_size': 512, 'amount_loss_weight': 0.5}
Epoch 1/15
    407/Unknown 146s 350ms/step - amount_output_loss: 2.6698 - event_output_loss: 0.6350 - event_output_pr_auc: 0.7376 - loss: 1.9699

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\trainers\epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

407/407 ━━━━━━━━━━━━━━━━━━━━ 160s 384ms/step - amount_output_loss: 2.2568 - event_output_loss: 0.6042 - event_output_pr_auc: 0.7681 - loss: 1.7372 - val_amount_output_loss: 1.7571 - val_event_output_loss: 0.5378 - val_event_output_pr_auc: 0.8031 - val_loss: 1.4318 - learning_rate: 1.0000e-04
Epoch 2/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 149s 366ms/step - amount_output_loss: 1.9677 - event_output_loss: 0.5719 - event_output_pr_auc: 0.8005 - loss: 1.5598 - val_amount_output_loss: 1.7446 - val_event_output_loss: 0.5282 - val_event_output_pr_auc: 0.8147 - val_loss: 1.4162 - learning_rate: 1.0000e-04
Epoch 3/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 149s 365ms/step - amount_output_loss: 1.9115 - event_output_loss: 0.5633 - event_output_pr_auc: 0.8101 - loss: 1.5226 - val_amount_output_loss: 1.7270 - val_event_output_loss: 0.5230 - val_event_output_pr_auc: 0.8195 - val_loss: 1.4016 - learning_rate: 1.0000e-04
Epoch 4/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 151s 371ms/step - amount_output_loss: 1.8781 - event_output_loss: 0.5585 - event_output_pr_auc: 0.8167 - loss: 1.5012 - val_amount_output_loss: 1.7034 - val_event_output_loss: 0.5203 - val_event_output_pr_auc: 0.8214 - val_loss: 1.3870 - learning_rate: 1.0000e-04
Epoch 5/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 149s 366ms/step - amount_output_loss: 1.8536 - event_output_loss: 0.5545 - event_output_pr_auc: 0.8216 - loss: 1.4850 - val_amount_output_loss: 1.7136 - val_event_output_loss: 0.5210 - val_event_output_pr_auc: 0.8211 - val_loss: 1.3925 - learning_rate: 1.0000e-04
Epoch 6/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 148s 364ms/step - amount_output_loss: 1.8390 - event_output_loss: 0.5519 - event_output_pr_auc: 0.8247 - loss: 1.4751 - val_amount_output_loss: 1.6988 - val_event_output_loss: 0.5204 - val_event_output_pr_auc: 0.8212 - val_loss: 1.3846 - learning_rate: 1.0000e-04
Epoch 7/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 149s 367ms/step - amount_output_loss: 1.8277 - event_output_loss: 0.5490 - event_output_pr_auc: 0.8283 - loss: 1.4666 - val_amount_output_loss: 1.6856 - val_event_output_loss: 0.5195 - val_event_output_pr_auc: 0.8224 - val_loss: 1.3769 - learning_rate: 1.0000e-04
Epoch 8/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 155s 380ms/step - amount_output_loss: 1.8063 - event_output_loss: 0.5458 - event_output_pr_auc: 0.8318 - loss: 1.4526 - val_amount_output_loss: 1.6997 - val_event_output_loss: 0.5209 - val_event_output_pr_auc: 0.8206 - val_loss: 1.3851 - learning_rate: 1.0000e-04
Epoch 9/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 0s 339ms/step - amount_output_loss: 1.8134 - event_output_loss: 0.5448 - event_output_pr_auc: 0.8339 - loss: 1.4515
Epoch 9: ReduceLROnPlateau reducing learning rate to 4.999999873689376e-05.
407/407 ━━━━━━━━━━━━━━━━━━━━ 150s 368ms/step - amount_output_loss: 1.7945 - event_output_loss: 0.5435 - event_output_pr_auc: 0.8342 - loss: 1.4442 - val_amount_output_loss: 1.6942 - val_event_output_loss: 0.5220 - val_event_output_pr_auc: 0.8196 - val_loss: 1.3829 - learning_rate: 1.0000e-04
Epoch 10/15
407/407 ━━━━━━━━━━━━━━━━━━━━ 153s 375ms/step - amount_output_loss: 1.7749 - event_output_loss: 0.5411 - event_output_pr_auc: 0.8367 - loss: 1.4322 - val_amount_output_loss: 1.6949 - val_event_output_loss: 0.5195 - val_event_output_pr_auc: 0.8223 - val_loss: 1.3812 - learning_rate: 5.0000e-05
Epoch 10: early stopping
Restoring model weights from the end of the best epoch: 7.
Validation RMSE: 167627.145356
Validation MAE: 28048.453167
Validation R²: 0.075163

Trial 15 of 15
{'tweedie_power': 1.3, 'spatial_dropout': 0.2, 'lstm_units_2': 32, 'lstm_units_1': 64, 'lstm_dropout': 0.2, 'learning_rate': 0.0003, 'dense_units_2': 16, 'dense_units_1': 32, 'dense_dropout': 0.25, 'clipnorm': 1.0, 'batch_size': 256, 'amount_loss_weight': 5.0}
Epoch 1/15
    813/Unknown 104s 123ms/step - amount_output_loss: 0.8435 - event_output_loss: 0.7192 - event_output_pr_auc: 0.6135 - loss: 4.9365

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\trainers\epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

814/814 ━━━━━━━━━━━━━━━━━━━━ 115s 137ms/step - amount_output_loss: 0.7090 - event_output_loss: 0.6726 - event_output_pr_auc: 0.6717 - loss: 4.2248 - val_amount_output_loss: 0.4277 - val_event_output_loss: 0.5680 - val_event_output_pr_auc: 0.7934 - val_loss: 2.7266 - learning_rate: 3.0000e-04
Epoch 2/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 104s 127ms/step - amount_output_loss: 0.6062 - event_output_loss: 0.5944 - event_output_pr_auc: 0.7735 - loss: 3.6293 - val_amount_output_loss: 0.4138 - val_event_output_loss: 0.5377 - val_event_output_pr_auc: 0.8165 - val_loss: 2.6261 - learning_rate: 3.0000e-04
Epoch 3/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 107s 132ms/step - amount_output_loss: 0.5893 - event_output_loss: 0.5821 - event_output_pr_auc: 0.7917 - loss: 3.5353 - val_amount_output_loss: 0.4292 - val_event_output_loss: 0.5323 - val_event_output_pr_auc: 0.8226 - val_loss: 2.6980 - learning_rate: 3.0000e-04
Epoch 4/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 107s 132ms/step - amount_output_loss: 0.5834 - event_output_loss: 0.5767 - event_output_pr_auc: 0.7982 - loss: 3.4990 - val_amount_output_loss: 0.4147 - val_event_output_loss: 0.5297 - val_event_output_pr_auc: 0.8254 - val_loss: 2.6226 - learning_rate: 3.0000e-04
Epoch 5/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 108s 133ms/step - amount_output_loss: 0.5819 - event_output_loss: 0.5741 - event_output_pr_auc: 0.8025 - loss: 3.4901 - val_amount_output_loss: 0.4073 - val_event_output_loss: 0.5239 - val_event_output_pr_auc: 0.8280 - val_loss: 2.5792 - learning_rate: 3.0000e-04
Epoch 6/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 112s 138ms/step - amount_output_loss: 0.5690 - event_output_loss: 0.5720 - event_output_pr_auc: 0.8044 - loss: 3.4234 - val_amount_output_loss: 0.4174 - val_event_output_loss: 0.5279 - val_event_output_pr_auc: 0.8265 - val_loss: 2.6338 - learning_rate: 3.0000e-04
Epoch 7/15
813/814 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - amount_output_loss: 0.5683 - event_output_loss: 0.5722 - event_output_pr_auc: 0.8046 - loss: 3.4137
Epoch 7: ReduceLROnPlateau reducing learning rate to 0.0001500000071246177.
814/814 ━━━━━━━━━━━━━━━━━━━━ 105s 128ms/step - amount_output_loss: 0.5674 - event_output_loss: 0.5712 - event_output_pr_auc: 0.8049 - loss: 3.4135 - val_amount_output_loss: 0.4126 - val_event_output_loss: 0.5264 - val_event_output_pr_auc: 0.8266 - val_loss: 2.6085 - learning_rate: 3.0000e-04
Epoch 8/15
814/814 ━━━━━━━━━━━━━━━━━━━━ 128s 157ms/step - amount_output_loss: 0.5641 - event_output_loss: 0.5679 - event_output_pr_auc: 0.8076 - loss: 3.3939 - val_amount_output_loss: 0.4075 - val_event_output_loss: 0.5238 - val_event_output_pr_auc: 0.8278 - val_loss: 2.5797 - learning_rate: 1.5000e-04
Epoch 8: early stopping
Restoring model weights from the end of the best epoch: 5.
Validation RMSE: 166676.506205
Validation MAE: 29910.488495
Validation R²: 0.085623

Top LSTM tuning results:

,trial,validation_rmse,validation_mae,validation_r2,best_validation_loss,epochs_used,tweedie_power,spatial_dropout,lstm_units_2,lstm_units_1,lstm_dropout,learning_rate,dense_units_2,dense_units_1,dense_dropout,clipnorm,batch_size,amount_loss_weight
0,9,"166,661.34276","28,067.72140",0.08579,0.85624,11,1.50000,0.20000,64,32,0.10000,0.00300,16,64,0.10000,0.50000,512,0.50000
1,15,"166,676.50620","29,910.48850",0.08562,2.57922,8,1.30000,0.20000,32,64,0.20000,0.00030,16,32,0.25000,1.00000,256,5.00000
2,10,"166,977.63745","29,864.24202",0.08232,1.11313,12,1.10000,0.10000,64,64,0.30000,0.00010,64,64,0.40000,1.00000,512,2.00000
3,7,"167,076.60573","29,223.58775",0.08123,0.82439,4,1.10000,0.00000,64,64,0.30000,0.00300,32,32,0.40000,1.00000,1024,1.00000
4,8,"167,167.38934","27,720.13615",0.08023,1.96293,8,1.50000,0.00000,32,128,0.20000,0.00010,16,128,0.10000,1.00000,1024,2.00000
5,11,"167,330.80521","27,190.25445",0.07843,2.62794,8,1.30000,0.00000,16,128,0.20000,0.00010,16,128,0.40000,2.00000,1024,5.00000
6,1,"167,340.98376","29,550.78076",0.07832,1.35059,15,1.70000,0.10000,16,64,0.10000,0.00030,16,64,0.40000,2.00000,256,0.50000
7,2,"167,475.93471","29,109.70099",0.07683,0.81339,15,1.10000,0.20000,32,64,0.10000,0.00030,16,32,0.25000,0.50000,1024,1.00000
8,13,"167,610.54200","30,302.61749",0.07535,1.37661,7,1.30000,0.10000,32,32,0.30000,0.00030,64,64,0.40000,2.00000,256,2.00000
9,14,"167,627.14536","28,048.45317",0.07516,1.37693,10,1.70000,0.00000,32,128,0.20000,0.00010,16,32,0.10000,1.00000,512,0.50000

Best validation RMSE: 166661.34275619176

Best parameters:
{'tweedie_power': 1.5, 'spatial_dropout': 0.2, 'lstm_units_2': 64, 'lstm_units_1': 32, 'lstm_dropout': 0.1, 'learning_rate': 0.003, 'dense_units_2': 16, 'dense_units_1': 64, 'dense_dropout': 0.1, 'clipnorm': 0.5, 'batch_size': 512, 'amount_loss_weight': 0.5}

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\saving\saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 34 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

88/88 ━━━━━━━━━━━━━━━━━━━━ 8s 86ms/step

C:\Users\admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\keras\src\trainers\epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

88/88 ━━━━━━━━━━━━━━━━━━━━ 8s 89ms/step

Final selected LSTM hurdle model
Validation RMSE: 166661.342756
Validation MAE: 28067.721400
Validation R²: 0.085790

Test RMSE: 484876.189514
Test MAE: 50781.574193
Test R²: 0.032523
CPU times: total: 23h 51min 49s
Wall time: 5h 11min 32s